### ISSUE TITLE
jsdoc won't work with (function(window) {})() type of scripts (ECMA5 block definition)

### ISSUE THREAD

**Issue by coreorm** [jsdoc3/jsdoc#1161] opened 2016-02-25 04:39 UTC
as we know, for modules that are compatible with both node and windows, we use
```
(function (window) {
  var foo = function () {
    ...
  }
  ...
  if (exports) exports = foo;
})()
```

And jsdoc will simply ignore this syntax. can you guys please fix it.

**Comment by wvankuipers** [comment] 2016-02-26 12:35
I have exactly the same issue, jsdoc wil simply put the complete file inside the generated HTML file

**Comment by hegemonic** [comment] 2016-08-31 00:58
Duplicate of #456.

**Closed by hegemonic** 2016-08-31 00:58 UTC

**Comment by BillyWM** [comment] 2016-12-08 19:20
Does #456 actually contain a resolution for documenting IIFEs?

We have a structure that's basically
```Javascript
MySingleton = (function() {
    innerObject = {
        someMethod: function(x, y, z) {
        }
    }
    ....

   return innerObject;
})();
```

Now, comments on the structure aside (I don't like this but I'm not being paid to refactor this and bug test all the potential regressions, so that's not an option at the moment), I would expect that I could just tell JSDoc that the inner methods end up accessible at e.g. ```MySingleton.someMethod()``` but JSDoc doesn't seem to get the hint. This is not a "module", and not really a namespace, so those aren't appropriate (not that they seem to work anyway).

**Comment by hegemonic** [comment] 2016-12-10 02:39
@BillyWM If you don't mind documenting `MySingleton` as a class, this works for me:

```js
/**
 * Singleton.
 * @class
 */
var MySingleton = (function() {
    var innerObject = {
        /**
         * Method.
         * @param {string} x - X param.
         * @param {string} y - Y param.
         * @param {string} z  - Z param.
         * @memberof MySingleton
         */
        someMethod: function(x, y, z) {
        }
    };

   return innerObject;
})();
```

**Comment by BillyWM** [comment] 2016-12-10 22:13
Yes it seems this was VSCode's fault for having poor JSDoc support. I tried Webstorm and it gave me the right hints. My mistake.
