### ISSUE TITLE
Doesn't support JSX

### ISSUE THREAD

**Issue by yordis** [jsdoc3/jsdoc#1001] opened 2015-05-07 07:07 UTC
I am trying to use jsdoc with ```.jsx``` files and seems doesn't work. I can build the ```.jsx``` files and then try to generate the documentation but I really don't like that solution.

Are you going to support ```.jsx```?

**Comment by hegemonic** [comment] 2015-05-10 00:16
I don't currently have plans to support JSX. However, it would be possible to do so, since JSDoc uses a JS parser that supports JSX.

Keeping this open as an enhancement request.

**Comment by hegemonic** [comment] 2015-05-10 00:21
I should add that I have some reservations about supporting JSX. The biggest is that JSDoc would be stuck using a JavaScript parser that support JSX, which would limit our options if we needed to change parsers in the future. (And we've already changed parsers twice, so there's a reasonably high likelihood that this will happen again.)

**Comment by wintermuted** [comment] 2015-05-27 17:06
Would love to see this :+1:

**Comment by gcedo** [comment] 2015-06-02 12:46
+1

**Comment by tparnell8** [comment] 2015-06-04 13:53
:+1:

**Comment by ctumolosus** [comment] 2015-06-17 12:22
I created a plugin ([`jsdoc-jsx`](https://www.npmjs.com/package/jsdoc-jsx)), where I manage to get this to work by transforming my JSX files with esprima before they are processed by JSDoc.

**Comment by yordis** [comment] 2015-06-17 23:39
@ctumolosus That's awesome but I would like to see this on JSDoc too. 

Great job!

**Comment by yaycmyk** [comment] 2015-06-29 16:16
> The biggest is that JSDoc would be stuck using a JavaScript parser that supports JSX, which would limit our options if we needed to change parsers in the future. 

@hegemonic Totally understand where you're coming from, but the developer interest in JSX is so high now and going forward. Most of the actively maintained parsers do support JSX for free now, like https://github.com/eslint/espree.

**Comment by yordis** [comment] 2015-07-17 04:18
@hegemonic any update in this? Even Babel is supporting JSX so I think like @yaycmyk  this feature is on demand right now

**Comment by ariporad** [comment] 2015-08-02 19:06
+1 @hegemonic, any update?

**Comment by ewaldman** [comment] 2015-08-11 16:41
Anyone know whether jsdoc-jsx works together with grunt-jsdoc?
I tried it but got an error that points to jsdoc-jsx\node_modules\jstransform\src\simple.js:105:28

Thank you

**Comment by hegemonic** [comment] 2015-08-13 23:50
I've added JSX support on GitHub master. JSX support will be included in JSDoc 3.4.0. For now, if you want JSX support, use GitHub master, not the npm version of JSDoc.

It's very likely that the current implementation has some bugs. If JSDoc can't handle your JSX code, please file a new issue, and include a code sample that reproduces the error.

**Closed by hegemonic** 2015-08-13 23:50 UTC
Labels: feature

**Comment by ewaldman** [comment] 2015-08-14 15:09
Thanks for adding jsx to master. I used that version and it gave documentation. however for some of the classes it gave the following warning : WARNING: JSDoc does not currently handle ArrowFunctionExpression nodes. So how do I deal with that? arrow functions are an integral part of my code. 
Thank you

**Comment by hegemonic** [comment] 2015-08-18 03:17
@ewaldman JSDoc currently ignores arrow functions. This is a temporary limitation. In many cases, it won't affect your documentation at all.

**Comment by yaycmyk** [comment] 2015-08-20 16:00
@hegemonic Is there a flag that needs to be flipped to enable JSX support? Running the latest 4.0 beta locally and they're still not being processed :(

My config is
```json
{
    "opts": {
        "template": "../node_modules/minami"
    },
    "plugins": []
}
```

And running it with
```bash
find src -type f -name '*.js' -o -name '*.jsx' | xargs jsdoc -d docs/api -c docs/jsdoc.json
```

I can confirm that the `find` is definitely picking up the jsx files

**Comment by hegemonic** [comment] 2015-08-20 17:51
@yaycmyk This issue was caused by a silly oversight on my part--by default, JSDoc still wasn't looking for files with the extension `.jsx`. This is now fixed on GitHub master.

**Comment by yaycmyk** [comment] 2015-08-20 17:52
Ahh got it! Thank you very much :)
