### ISSUE TITLE
MPL-2.0 license tag will be interpreted as a jsdoc tag since 3.5

### ISSUE THREAD

**Issue by interpretor** [jsdoc3/jsdoc#1403] opened 2017-07-13 10:30 UTC
### Input code

```js
/*
 * Copyright (c) 2017 Foo Bar
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

const dgram = require('dgram');
```

### JSDoc configuration

default

### JSDoc debug output

```
Your debug output here
```

### Expected behavior

It should not add `dgram` to the Global Members.

### Current behavior

Jsdoc adds `dgram` to the Global Members.
![Imgur](http://i.imgur.com/F5lm4iW.jpg)

### Your environment

| Software         | Version
| ---------------- | -------
| JSDoc            | 3.5.2
| Node.js          | 6.11.1
| npm              | 5.2.0
| Operating system | Linux x64

**Comment by hegemonic** [comment] 2017-07-13 18:18
Duplicate of #1398. The fix will be included in JSDoc 3.5.3.

**Closed by hegemonic** 2017-07-13 18:18 UTC
