### ISSUE TITLE
Use jsdoc as a node-module in js scripts

### ISSUE THREAD

**Issue by pmeijer** [jsdoc3/jsdoc#1322] opened 2017-02-02 21:39 UTC
Is there a way to use jsdoc from another js-file and call the execution by passing variables?

Currently when jsdoc is required the cli is automatically executed and looks for the arguments from argv.

We have a use-case where we the template in the jsdoc_conf.json references a file inside a node_module. When our postinstall script runs jsdoc cannot find the referenced file since node_module path does no longer apply.

**Comment by hegemonic** [comment] 2017-02-10 00:36
No, this isn't currently possible, sorry.

This issue is a duplicate of #938.

**Closed by hegemonic** 2017-02-10 00:36 UTC
