### ISSUE TITLE
"defaultvalue" not strictly correct

### ISSUE THREAD

**Issue by 75lb** [jsdoc3/jsdoc#900] opened 2015-01-31 23:16 UTC
with this JS: 
```js
/**
@enum {number}
*/
var eSomething = {
    one: 1,
    two: 2,
    three: 3
};
```

the output from `jsdoc -X` states that the `defaultvalue` of `one` is `"1"` - it's not `"1"`, it is `1` (i.e. a `number`, not a `string` value). 

this doesn't sound like a big deal but, in my app, i want to accurately report the type of the `defaultvalue`.. I `JSON.stringify` the `defaultvalue` to return a string which accurately reflects it's type.. if this issue was resolved, my app would output this: 

| Property | Default |
| --- | --- |
| one | `1` | 
| two | `2` | 
| three | `3` | 

but i currently get this, which is inaccurate:

| Property | Default |
| --- | --- |
| one | `"1"` | 
| two | `"2"` | 
| three | `"3"` |

**Comment by 75lb** [comment] 2015-02-01 09:50
this is the issue that led me to file the report.. i have var like this (containing a unicode symbol):
```js
/**
@type {string}
@default
*/
var whatev = "\u001b[30m";
```

the default value of `whatev` is correctly picked up by `@default`, but in the html output (and my app) it is displayed as `[30m`.. 

if I `JSON.stringify` the `defaultvalue` i get the correct value of `"\u001b[30m"`, which led me to discover the issue reported above..

**Comment by hegemonic** [comment] 2015-02-01 16:58
Confirmed. The fix for this will take a little time but is pretty straightforward.

**Comment by 75lb** [comment] 2015-02-01 17:25
great! pleased to hear it will get looked at :+1:

**Comment by hegemonic** [comment] 2015-02-01 21:39
Fixed on master and releases/3.3. (It didn't take quite as long as I expected!) The fix will be in JSDoc 3.3.0.

**Comment by hegemonic** [comment] 2015-02-01 21:40
Incidentally, the string `\u001b[30m` will still appear in the docs as `[30m`, because `\u001b` is the non-printing `ESC` character.

**Comment by 75lb** [comment] 2015-02-02 21:31
yes, `\u001b` is unprintable but the reader is not interested in how it prints, just interested in the default value (which is not `[30m` as displayed) .. so i output JSON.stringify(defaultvalue) to get `"\\u001b[30m"` (which is printable)

in other news, sadly your wonderful new fix does not work with @param defaults.. so this JS returns a defaultvalue of `"11"`, despite the type being a `number`:
```js
/**
@param [val=11] {number}
*/
function blah(val){}
```

this is an awkward one..

**Comment by hegemonic** [comment] 2015-02-02 23:13
Thanks for pointing out the issue with `@param` tags. Reopening until that's sorted.

**Comment by 75lb** [comment] 2015-02-02 23:41
ok thanks.. i appreciate this is an awkward one.. in the meantime i've implemented a work around (involving inspecting the value of `type.names[0]` before deciding whether to stringify `defaultvalue` or not.. hacky but unfortunately i need the stringify to correctly represent defaults with unprintables..)

**Comment by hegemonic** [comment] 2015-02-03 00:29
This is now fixed, sort of. JSDoc will now try to infer the type of default values for `@param` and `@property`. Sometimes this might conflict with the documented type, though; for example, if you write `@param {string} [foo=true]`, JSDoc will document the default value as the boolean `true` rather than the string `"true"`.

In theory, we could get a little fancier and use the type expression to guess the default value's type more accurately. In practice, this would require a lot of refactoring for a very small benefit. I'll file a new issue for this, just to capture the issue, but I'm unlikely to work on it anytime soon.

**Closed by hegemonic** 2015-02-03 00:29 UTC
Labels: bugfix
