### ISSUE TITLE
Documenting a function and using it as a namespace seams impossible

### ISSUE THREAD

**Issue by Cobraeti** [jsdoc3/jsdoc#1203] opened 2016-04-26 20:45 UTC
Hi,
I was not able to find a way to document a function and then use it as a namespace for other ones...
I think the best way to explain what I try to do is to give you an exemple. So here is a sample code of what I'm working on:

``` javascript
/**
* Simple test module
* @module test
**/

/**
* Simple log function
* @param {String} message Message to log
**/
/**
* Namespace for log shortcuts
* @namespace
**/
var log = function(message) {
  console.log(message);
}

/**
* Simple debug shortcut
* @param {String} message Message to log
**/
log.debug = function(message) {
  log('<debug> ' + message + ' <debug>');
}

/**
* Simple info shortcut
* @param {String} message Message to log
**/
log.info = function(message) {
  log('<info> ' + message + ' <info>');
}

/**
* Simple access function
* @param {String} message Message to log
**/
/**
* Namespace for access shortcuts
* @namespace
**/
var access = function(message) {
  console.access(message);
}

/**
* Simple debug shortcut
* @param {String} message Message to access
**/
access.debug = function(message) {
  access('<debug> ' + message + ' <debug>');
}

/**
* Simple info shortcut
* @param {String} message Message to access
**/
access.info = function(message) {
  access('<info> ' + message + ' <info>');
}


module.exports.log = log;
module.exports.access = access;
```

Running JSDoc on this code gives me the following doc hierarchy:
<h2>Home</h2><h3>Modules</h3><ul><li>test</li></ul><h3>Namespaces</h3><ul><li>access<ul><li>debug</li><li>info</li></ul></li><li>log<ul><li>debug</li><li>info</li></ul></li></ul>
After inverting function definition and namespace it gives this hierarchy:
<h2>Home</h2><h3>Modules</h3><ul><li>test<ul><li>access</li><li>log</li></ul></li></ul>
And finaly, combining the namespace and function tags gives me the same hierarchy as for the sample code...

What am I doing wrong? Is it even possible?
Any suggestion and tricks are welcome ;)

P.S.: I would prefer not to change the functions tree, but it is not too late if there is no other solution. I thought this tree was more user friendly to present my functions, but it is less important than a good and complete doc.

**Comment by Cobraeti** [comment] 2016-05-23 12:32
Hi,
I just want to say that I now use a Class hierarchy, which is more simpler to document.
That doesn't solve my shortcut documentation problem, but this reflects my hierarchy a little better while waiting for a better solution...

**Comment by hegemonic** [comment] 2017-07-04 20:22
Duplicate of #955.

**Closed by hegemonic** 2017-07-04 20:22 UTC
