### ISSUE TITLE
`export default class` produces incorrect name

### ISSUE THREAD

**Issue by englercj** [jsdoc3/jsdoc#1252] opened 2016-09-01 20:40 UTC
Using master, if I use the syntax `export default class X {}` instead of `class X {}; export default X;` the naming is incorrect. It always comes out as `exports` as the name, and `module.exports` as the longname. This causes all my classes to pile up, and even place many members on the global namespace in the generated documentation HTML.

For example, this class:

```js
/**
 * A cool class
 */
export default class MyClass {
    /**
     * Totally constructs a MyClass
     */
    constructor()
    {
        /**
         * @member {number}
         */
        this.anumber = 0;
    }
}
```

Generates this description (`-X`):

```
[
    {
        "comment": "",
        "meta": {
            "range": [
                24,
                216
            ],
            "filename": "jsdoc-test.js",
            "lineno": 4,
            "path": "C:\\Users\\cengler\\repos\\fae",
            "code": {
                "id": "astnode100000001",
                "name": "module.exports",
                "type": "ClassDeclaration"
            }
        },
        "undocumented": true,
        "name": "exports",
        "longname": "module.exports",
        "kind": "class",
        "memberof": "module",
        "scope": "static"
    },
    {
        "comment": "/**\n * A cool class\n */",
        "meta": {
            "range": [
                39,
                216
            ],
            "filename": "jsdoc-test.js",
            "lineno": 4,
            "path": "C:\\Users\\cengler\\repos\\fae",
            "code": {
                "id": "astnode100000002",
                "name": "module.exports",
                "type": "ClassDeclaration",
                "paramnames": []
            }
        },
        "classdesc": "A cool class",
        "name": "exports",
        "longname": "module.exports",
        "kind": "class",
        "memberof": "module",
        "scope": "static",
        "description": "Totally constructs a MyClass",
        "params": []
    },
    {
        "comment": "/**\n     * Totally constructs a MyClass\n     */",
        "meta": {
            "range": [
                111,
                214
            ],
            "filename": "jsdoc-test.js",
            "lineno": 8,
            "path": "C:\\Users\\cengler\\repos\\fae",
            "code": {
                "id": "astnode100000005",
                "name": "module.exports",
                "type": "MethodDefinition",
                "paramnames": []
            },
            "vars": {
                "": null
            }
        },
        "description": "Totally constructs a MyClass",
        "name": "exports",
        "longname": "module.exports",
        "kind": "class",
        "memberof": "module",
        "scope": "static",
        "params": [],
        "undocumented": true
    },
    {
        "comment": "/**\n         * @member {number}\n         */",
        "meta": {
            "range": [
                191,
                207
            ],
            "filename": "jsdoc-test.js",
            "lineno": 13,
            "path": "C:\\Users\\cengler\\repos\\fae",
            "code": {
                "id": "astnode100000010",
                "name": "this.anumber",
                "type": "Literal",
                "value": 0,
                "paramnames": []
            }
        },
        "kind": "member",
        "type": {
            "names": [
                "number"
            ]
        },
        "name": "anumber",
        "longname": "module.exports#anumber",
        "memberof": "module.exports",
        "scope": "instance"
    },
    {
        "kind": "package",
        "longname": "package:undefined",
        "files": [
            "C:\\Users\\cengler\\repos\\fae\\jsdoc-test.js"
        ]
    }
]
```

However, if I change the export syntax it gets the proper name:

```js
/**
 * A cool class
 */
class MyClass {
    /**
     * Totally constructs a MyClass
     */
    constructor()
    {
        /**
         * @member {number}
         */
        this.anumber = 0;
    }
}

export default MyClass;
```

Here is the description (`-X`):

```
[
    {
        "comment": "/**\n * A cool class\n */",
        "meta": {
            "range": [
                24,
                201
            ],
            "filename": "jsdoc-test.js",
            "lineno": 4,
            "path": "C:\\Users\\cengler\\repos\\fae",
            "code": {
                "id": "astnode100000001",
                "name": "MyClass",
                "type": "ClassDeclaration",
                "paramnames": []
            }
        },
        "classdesc": "A cool class",
        "name": "MyClass",
        "longname": "MyClass",
        "kind": "class",
        "scope": "global",
        "description": "Totally constructs a MyClass",
        "params": []
    },
    {
        "comment": "/**\n     * Totally constructs a MyClass\n     */",
        "meta": {
            "range": [
                96,
                199
            ],
            "filename": "jsdoc-test.js",
            "lineno": 8,
            "path": "C:\\Users\\cengler\\repos\\fae",
            "code": {
                "id": "astnode100000004",
                "name": "MyClass",
                "type": "MethodDefinition",
                "paramnames": []
            },
            "vars": {
                "": null
            }
        },
        "description": "Totally constructs a MyClass",
        "name": "MyClass",
        "longname": "MyClass",
        "kind": "class",
        "scope": "global",
        "params": [],
        "undocumented": true
    },
    {
        "comment": "/**\n         * @member {number}\n         */",
        "meta": {
            "range": [
                176,
                192
            ],
            "filename": "jsdoc-test.js",
            "lineno": 13,
            "path": "C:\\Users\\cengler\\repos\\fae",
            "code": {
                "id": "astnode100000009",
                "name": "this.anumber",
                "type": "Literal",
                "value": 0,
                "paramnames": []
            }
        },
        "kind": "member",
        "type": {
            "names": [
                "number"
            ]
        },
        "name": "anumber",
        "longname": "MyClass#anumber",
        "memberof": "MyClass",
        "scope": "instance"
    },
    {
        "comment": "",
        "meta": {
            "range": [
                203,
                226
            ],
            "filename": "jsdoc-test.js",
            "lineno": 17,
            "path": "C:\\Users\\cengler\\repos\\fae",
            "code": {
                "id": "astnode100000014",
                "name": "module.exports",
                "type": "Identifier"
            }
        },
        "undocumented": true,
        "name": "exports",
        "longname": "module.exports",
        "kind": "member",
        "memberof": "module",
        "scope": "static"
    },
    {
        "kind": "package",
        "longname": "package:undefined",
        "files": [
            "C:\\Users\\cengler\\repos\\fae\\jsdoc-test.js"
        ]
    }
]
```

Unfortunately the first one causes all kinds of issues with properties and other things due to the longname often being `module.exports`. I saw a few other similar issues that said this was fixed, but this still happens for me on latest master.

**Comment by Reinmar** [comment] 2016-09-07 14:08
I've got the same problem. For this:

```js
/** @module ckeditor5/foo */

/**
 * The foo class.
 */
export default class Foo {
	/**
	 * The foo constructor.
	 */
	constructor() {

	}

	/**
	 * The bar method.
	 *
	 * @returns {String}
	 */
	bar() {

	}
}
```

I get this on the current master:

![screen shot 2016-09-07 at 16 05 17](https://cloud.githubusercontent.com/assets/156149/18314812/e62ca81e-7514-11e6-9bc0-5d82026fd02b.png)

And this on 3.4.0:

![screen shot 2016-09-07 at 16 06 14](https://cloud.githubusercontent.com/assets/156149/18314844/0f5c2db8-7515-11e6-848a-14a7e9f7fe13.png)

Both results are unfortunately totally incorrect.

**Comment by Reinmar** [comment] 2016-09-07 14:21
There's a workaround described in https://github.com/jsdoc3/jsdoc/issues/1137#issuecomment-174829004

**Comment by hegemonic** [comment] 2016-09-12 23:05
Duplicate of #1137.

**Closed by hegemonic** 2016-09-12 23:05 UTC

**Comment by leeyeh** [comment] 2016-12-14 09:11
I ran into this issue with v3.4.1

**Comment by englercj** [comment] 2016-12-15 03:03
@leeyeh https://github.com/jsdoc3/jsdoc/issues/1137#issuecomment-254089910
