### ISSUE TITLE
ES 6 module exporting ES 6 class not correctly parsed

### ISSUE THREAD

**Issue by bjornharrtell** [jsdoc3/jsdoc#1113] opened 2015-11-20 22:23 UTC
The code below will generate a module page "test" with the title "Class: module:test" and an undocumented constructor with content "new module:test()" but also a separate class page "Test" with the actual constructor documentation.

```js
/** @module */

/** Test class */
export default class Test {
  
  /** Test constructor */
  constructor(test) { }
}
```

This is on released jsdoc 3.4.0.

**Comment by carlosdubus** [comment] 2015-11-21 04:21
+1 I just ran into this.

If you remove the export keyword, it works fine. So the bug has to do with the export.

**Comment by hegemonic** [comment] 2015-11-25 23:47
Confirmed. It looks like we're setting the wrong longname for the class in this case. I'll investigate.

**Comment by bjornharrtell** [comment] 2015-11-26 18:48
I also noticed that exporting an anonymous class is problematic. This code:

```js
/** @module */

/** Test class */
export default class { }
```

Results in `TypeError: Cannot read property 'type' of null` at `astnode.js:113`.

I'll try to make proper test cases out of these.

**Comment by bjornharrtell** [comment] 2015-11-26 18:57
I find it hard to understand where to add tests for "implicit" parsing like this where there is no export jsdoc tag. The spec exportstag.js only seem to consider the explicit use of the jsdoc tag and should perhaps stay that way?

**Comment by hegemonic** [comment] 2015-11-29 22:56
The crash should be fixed on master. (That commit shows you how I handle test fixtures for things like this.) The original issue still remains to be fixed.

**Comment by hegemonic** [comment] 2015-12-03 14:05
The original issue is now fixed on master. JSDoc 3.4.1 will include the fix.

**Closed by hegemonic** 2015-12-03 14:05 UTC
Labels: bugfix
