### ISSUE TITLE
`@lends` doesn't work when the `new` operator apears before an expression

### ISSUE THREAD

**Issue by kerimdzhanov** [jsdoc3/jsdoc#1130] opened 2015-12-19 20:39 UTC
The `@lends` tag won't mark object if `new` operator appears, here is an example:

``` js
'use strict';

var mongoose = require('mongoose'),
    Schema = mongoose.schema,
    ObjectId = Schema.ObjectId;

/**
 * @class User
 */
var UserSchema = new Schema(/** @lends User# */{
  /** @type String */
  email: String,

  /** @type String */
  passwordHash: String,

  /** @type String */
  passwordSalt: String,

  /** @type Role[] */
  roles: [{ type: ObjectId, ref: 'Role' }]
});
```

And if we omit the `new` operator (fortunately some libs supports factory-like constructors, as well as mongoose), the `@lends` works as expected.

**Comment by hegemonic** [comment] 2015-12-21 23:53
Very strange. Thanks for reporting this issue--this is definitely not the intended behavior. I'll investigate.

**Comment by kerimdzhanov** [comment] 2015-12-21 23:55
Thank you!

**Comment by purtuga** [comment] 2015-12-30 21:07
Just switched over a project to use jsdoc3 and am experiencing a similar issue... none of the class members are being output when the `@lends` is used. My case is slightly different from what @kerimdzhanov reported, but I think it may be related - thus why I did not open a new issue.

Here is an example:

```javascript
/**
 * A sliding panel widget.
 *
 * @class SlidingPanel
 *
 * @param {Object} options
 * @param {DOMElement} options.appendTo
 * @param {DOMElement} [options.content]
 * @param {String} [options.position="left"]
 *  Possible values: `left` (default), `right`.
 *
 */
SlidingPanel = /**@lends SlidingPanel.prototype*/{
    init: function(options){},
    
    /**
     * make panel visible
     */
    show: function(){}
}
```

Thanks.

/paul

**Comment by purtuga** [comment] 2016-03-31 22:58
Looks like there is a pending contribution to fix this.  Hope it gets accepted soon.

**Comment by jscharett** [comment] 2016-07-25 19:58
+1

**Comment by hegemonic** [comment] 2017-07-06 07:11
This issue is fixed on master—we now use the [Babylon](https://github.com/babel/babylon) parser and its built-in comment-attachment feature, rather than using custom code for attaching comments. The fix will be included in JSDoc 3.5.0.

**Closed by hegemonic** 2017-07-06 07:11 UTC
Labels: bugfix
