### ISSUE TITLE
Tutorial conf.json having parsing error

### ISSUE THREAD

**Issue by sakthiwhale** [jsdoc3/jsdoc#1364] opened 2017-05-08 15:48 UTC
I followed all the steps mentioned and still I get **"Unexpected token ? in JSON at position 0"** error when I have a conf.json file in my tutorials folder. If I remove the conf.json, it works perfect. But I need the conf.json.

I have a tutorials folder with .md files and a conf.json file which looks like this
```
{
    "name_of_tutorial": {
        "title": "Test Title" 
    } 
}
```

and in my jsdoc.json file looks like this
```
{
    "tags": {
        "allowUnknownTags": true,
        "dictionaries": ["jsdoc", "closure"]
    },
    "opts": {
        "recurse": true,
        "encoding": "utf8",
        "destination": "./docs",
        "readme": "./Content/tutorials/project_README.md",
        "tutorials": "./Content/tutorials"
    },
    "source": {
        "includePattern": ".+\\.js(doc|x)?$",
        "excludePattern": "(^|\\/|\\\\)_"
    },
    "plugins": [
        "plugins/markdown"
    ],
    "templates": {
        "cleverLinks": false,
        "monospaceLinks": false,
        "default": { }
    }
}
```

Looks like there is a problem when reading the file and parsing it as json.
Can you help me fix it?

**Comment by hegemonic** [comment] 2017-07-03 00:15
Duplicate of #1256 (which is now fixed on master).

**Closed by hegemonic** 2017-07-03 00:15 UTC
