### ISSUE TITLE
plugins search anomaly

### ISSUE THREAD

**Issue by pabigot** [jsdoc3/jsdoc#1097] opened 2015-10-24 16:16 UTC
From the [description](http://usejsdoc.org/about-plugins.html#creating-and-enabling-a-plugin) I would expect to be able to use:

    "plugins": ["plugins/markdown", "plugins/plugins_local"],

in `conf.json` and have JSDoc find both the `plugins/markdown` in the JSDoc directory and the `plugins_local` plugin in a local `plugins` in the directory containing the `conf.json` file.  This doesn't work:  JSDoc 3.3.3 fails to find `markdown` in the `plugins` adjacent to `conf.json` and aborts instead of continuing to look relative to the lower priority locations.

A work-around is to use a non-conflicting directory name to hold the local plugins:

    "plugins": ["plugins/markdown", "custom/plugins_local"],

**Comment by hegemonic** [comment] 2015-12-08 00:29
I think this is a duplicate of #1081, which is now fixed. Please let me know if you're still seeing this issue on GitHub master. The fix for #1081 will be included in JSDoc 3.4.1.

**Closed by hegemonic** 2015-12-08 00:29 UTC
