### ISSUE TITLE
Unsightly double-quotes in names in output

### ISSUE THREAD

**Issue by brennon** [jsdoc3/jsdoc#1078] opened 2015-09-29 19:12 UTC
I'm forced to use double quotes around the names I use, was discussed in #59. The matter of the double-quotes persisting in the output was discussed in this issue. The issue was closed, and the removal of the double-quotes was left for someone else to open another issue. I'd very much like to see that...they're really clogging up my display!

**Comment by hegemonic** [comment] 2015-12-08 00:35
Duplicate of #490.

**Closed by hegemonic** 2015-12-08 00:35 UTC
