### ISSUE TITLE
can you not use taffydb with specific url please?

### ISSUE THREAD

**Issue by mkuts12** [jsdoc3/jsdoc#1181] opened 2016-03-20 13:37 UTC
Hello, 

I work in a closed network and we have our own sinopia storage.

We can't use npm to install taffydb because we can't react github.

can you please consider using something else or use it from npm?

thanks!

**Comment by hegemonic** [comment] 2016-03-22 23:39
Duplicate of #961.

**Closed by hegemonic** 2016-03-22 23:39 UTC
