### ISSUE TITLE
jsdoc has a hard dep on github

### ISSUE THREAD

**Issue by 75lb** [jsdoc3/jsdoc#1153] opened 2016-02-01 08:08 UTC
jsdoc has Github dependency on `taffydb`.. sometimes Github goes down (as it did last week) making jsdoc (and downstream tools like jsdoc2md) uninstallable, until Github sort out their problem. 

Can the jsdoc project reference the taffydb npm module? It seems the fork it currently depends on is 4 years stale and only adds a readme and package.json (which are both present in taffy these days).

One other reason to change is performance, using github deps slows down the install process (as the code needs to be cloned/downloaded each time, whereas npm caches modules in `~/.npm`)

**Comment by timhemming-fico** [comment] 2016-02-16 13:55
This is an annoyance for our team too. Best to stick with NPM dependencies only for release builds.

**Comment by hegemonic** [comment] 2016-03-22 23:39
Duplicate of #961.

**Closed by hegemonic** 2016-03-22 23:39 UTC

**Comment by ogunheper** [comment] 2016-07-26 09:01
👍
