### ISSUE TITLE
[enhancement] Support programmatic interface

### ISSUE THREAD

**Issue by azweb76** [jsdoc3/jsdoc#1121] opened 2015-12-04 20:43 UTC
Several packages consume this package programmatically. Most of them have to call this via a spawned process with args. I recommend we expose a programmatic interface to allow this package to be consumed by other packages.

**Comment by hegemonic** [comment] 2015-12-05 14:28
Duplicate of #938.

**Closed by hegemonic** 2015-12-05 14:28 UTC
