### ISSUE TITLE
Not all link symbols are parsed

### ISSUE THREAD

**Issue by phun-ky** [jsdoc3/jsdoc#957] opened 2015-03-18 17:42 UTC
Possible related to #936 

With this code and jsdoc 3.2.2 (latest before 3.3.0):

    /**
      File for API alls.

      This module requires the global modules {@link moduleA}, {@link moduleB}, and the local modules {@link moduleC} and {@link moduleD}

      @file
      @author    ommitted
      @module    moduleAPI
      @requires  moduleA
      @requires  moduleB
      @requires  moduleC
      @requires  moduleD
     */

I get this doclet:

    {
        "comment": "/**\n  File for API alls.\n\n  This module requires the global modules {@link moduleA}, {@link moduleB}, and the local modules {@link moduleC} and {@link moduleD}\n\n  @file\n  @author    ommitted\n  @module    moduleAPI\n  @requires  moduleA\n  @requires  moduleB\n  @requires  moduleC\n  @requires  moduleD\n */",
        "meta": {
            "range": [
                0,
                503
            ],
            "filename": "moduleAPI.js",
            "lineno": 1,
            "path": "/home/alexander/Workspace/SiO1031_frontend/docstarget/my-account-apply-for-sublet/api",
            "code": {}
        },
        "description": "<p>File for API alls.</p>\n<p>  This module requires the global modules {@link moduleA}, {@link moduleB}, and the local modules {@link moduleC} and {@link moduleD}</p>",
        "name": "moduleAPI",
        "kind": "module",
        "preserveName": true,
        "author": [
            "ommitted"
        ],
        "requires": [
            "module:moduleA",
            "module:moduleB",
            "module:moduleC",
            "module:moduleD"
        ],
        "longname": "module:moduleAPI"
    },

and the links are not correctly converted in the html:

    <h1 class="page-title">Module: moduleAPI</h1>

    <section>
      <header>
        <h2>moduleAPI</h2>
      </header>

      <article>
        <div class="container-overview">
          <div class="description">
            <p>File for API alls. This module requires the global modules moduleA, moduleB, and the local modules moduleC and {@link moduleD2}</p>
          </div>

          <dl class="details">
            <dt class="tag-author">Author:</dt>

            <dd class="tag-author">
              <ul>
                <li>
                  <a href="mailto:omitted">ommitted</a>
                </li>
              </ul>
            </dd>

            <dt class="tag-source">Source:</dt>

            <dd class="tag-source">
              <ul class="dummy">
                <li>
                  <a href="moduleAPI.js.html">my-account-apply-for-sublet/api/moduleAPI.js</a>, <a href="moduleAPI.js.html#line1">line 1</a>
                </li>
              </ul>
            </dd>
          </dl>
        </div>

        <h3 class="subsection-title">Requires</h3>

        <ul>
          <li>module:moduleA</li>

          <li>
            <a href="module-moduleB.html">module:moduleB</a>
          </li>

          <li>
            <a href="module-moduleC.html">module:moduleC</a>
          </li>

          <li>
            <a href="module-moduleD2.html">module:moduleD2</a>
          </li>
        </ul>
      </article>
    </section>

I know it's a bit overload of code here, but this is the line I am noticing:

    ..al modules moduleC and {@link moduleD2}

**Comment by hegemonic** [comment] 2015-03-19 00:29
Yep, this is busted. Looks like a regression caused by 398595d796a2395a86d2158ab200b7bd922148b4.

**Comment by hegemonic** [comment] 2015-03-19 00:54
Fixed on master and releases/3.3. The fix will be included in JSDoc 3.3.0.

**Closed by hegemonic** 2015-03-19 00:54 UTC
Labels: bugfix
