### ISSUE TITLE
Loading templates doesn't seem to be able to load modules correctly

### ISSUE THREAD

**Issue by jonathanKingston** [jsdoc3/jsdoc#913] opened 2015-02-08 05:10 UTC
I can't seem to load templates of any kind with the following commands:

Adding in baseline into my node_modules:
```
jsdoc dist -t node_modules/jsdoc-baseline/ -d doc ./package.json ./README-doc.md
```
Got the following error:
```
js: "/usr/local/lib/node_modules/jsdoc/jsdoc.js", line 316: exception from uncaught JavaScript throw: Error: Unable to load template: Module "underscore-contrib" not found.
```

or

Copying default template to doc-template, even changing the include paths relative to the jsdoc directory.
```
jsdoc dist -t doc-template -d doc ./package.json ./README-doc.md
```

Got the following error:
```
js: "/usr/local/lib/node_modules/jsdoc/jsdoc.js", line 316: exception from uncaught JavaScript throw: Error: Unable to load template: Module "jsdoc/util/runtime" not found.
```

**Comment by hegemonic** [comment] 2015-02-08 20:58
Hmmm. Could you let me know which version of JSDoc you're using? (Run `jsdoc -v` to find that info.)

**Comment by jonathanKingston** [comment] 2015-02-08 22:36
@hegemonic sorry for the delay:

`JSDoc 3.3.0-beta1 (Wed, 21 Jan 2015 17:41:43 GMT)`

Thanks

**Comment by hegemonic** [comment] 2015-02-09 16:38
@jonathanKingston I'm not able to reproduce this issue. Here are the steps I took:

1. Installed JSDoc globally with `npm install -g jsdoc@3.3.0-beta1`.
2. Created a `~/tmp` directory.
3. Copied the default template to `~/tmp/template`, without making any changes to the template.
4. Created two dummy files: `~/tmp/test.js` and `~/tmp/README.md`.
5. Ran JSDoc: `jsdoc ./test.js ./README.md -t template/`.

Can you please try uninstalling JSDoc, then reinstalling and following these steps?

If you still can't get it to work, can you see if you can reproduce the problem on another machine?

**Comment by jonathanKingston** [comment] 2015-02-09 22:59
@hegemonic ok so that worked.
However with the same version in my sample code still had the same issue.

A resolution was removing  the node_module from the package.json I had installed and using the following command:
```
jsdoc dist -t node_modules/jsdoc-baseline/ -d doc ./README-doc.md
```
However the output looks broken and also the README output is HTML escaped.

---

So then I copied the default afain to doc-template:
```
 cp -r /home/jonathan/.node-packages/lib/node_modules/jsdoc/templates/default/ doc-template/
```
and ran:
```
jsdoc dist -t doc-template/ -d doc ./README-doc.md
```
---

The code I have is:
https://github.com/JetsonIO/jetson-javascript/tree/docsetup

Using the `make doc` command (I have both lines as I intended to have a lookup to the version number in the latest):
```
doc-build:
	jsdoc dist -t node_modules/jsdoc-baseline/ -d doc ./package.json ./README-doc.md;
	jsdoc dist -t node_modules/jsdoc-baseline/ -d doc ./README-doc.md;
```

Thanks

**Comment by hegemonic** [comment] 2015-02-10 00:23
@jonathanKingston It sounds like you're seeing "broken" output with the Baseline template. Please file issues for that in [hegemonic/jsdoc-baseline](https://github.com/hegemonic/jsdoc-baseline/issues).

Can you clarify what other issues, if any, you are currently having?

**Comment by jonathanKingston** [comment] 2015-02-11 00:26
@hegemonic Not seeing any now sorry the issue with the default in the end was the copy I made to that directory (Was tired).

So the issues are:

1.    Having JSDoc in your project locally causes these routing issues with the default template as mentioned at the start (Not sure if this is a common use case however might be nice to raise as another issue)
2.    Template HTML output issue with baseline which I think is a HTML escaping issue with the homepage, will re-raise in the other repo.

I'm not sure if you are interested in 1. however will re-raise the other issue in the correct repo.

Feel free to close this and let me know about 1. Thank you for all your help.

**Comment by jonathanKingston** [comment] 2015-02-11 01:22
I think 1. relates to using Makefile's to calculate the documentation; I'm not really sure why it would make a difference but it seems to.

**Comment by hegemonic** [comment] 2015-02-13 16:46
Sounds like this was a `Makefile` problem, so I'm closing this issue. Thanks for filing the new issue against Baseline.

**Closed by hegemonic** 2015-02-13 16:46 UTC
Labels: bugfix, needmoreinfo

**Comment by jonathanKingston** [comment] 2015-02-13 18:55
@hegemonic indeed it was, sorry I should have closed.
Thanks for the help.
