### ISSUE TITLE
Record Type doesn't work

### ISSUE THREAD

**Issue by klesh** [jsdoc3/jsdoc#1173] opened 2016-03-10 08:06 UTC
An object called 'myObj' with properties 'a' (a number), 'b' (a string) and 'c' (any type).

```
@param {{a: number, b: string, c}} myObj
```

output only as:

```
myObj   Object
```

Is it expected?

**Comment by 75lb** [comment] 2016-03-11 17:25
just spotted this too.. it's the same for @type.. 

this doclet
```
/**
 * @type {{ a: number, b: string, c}}
 */
var recordType = {}
```
produces this explain output
```
"type": {
      "names": [
        "Object"
      ]
    },
```

**Comment by agauthiez** [comment] 2016-03-11 17:33
As a workaround you can describe the object using `@typedef`, e.g.:
```
/**
  * @typedef {Object} method~myObj
  * @property {number} a - A number.
  * @property {string} b - A string.
  * @property {*} c - An "any-type" member.
  */
```
... and then:
```
@param {method~myObj} myObj - The record typed parameter.
```

**Comment by klesh** [comment] 2016-03-12 01:39
@agauthiez Yes, but typedef is tedious, and the type doc will be placed  in another page by jsdoc, I was hoping Record Type will place doc inline.

**Comment by hegemonic** [comment] 2017-07-07 05:10
Duplicate of #636.

**Closed by hegemonic** 2017-07-07 05:10 UTC
