### ISSUE TITLE
@lends ignores uncommented methods in Object literal, contradicting documentation

### ISSUE THREAD

**Issue by cefn** [jsdoc3/jsdoc#1265] opened 2016-09-20 10:38 UTC
JSDoc 3.4.1 (from npm) doesn't seem to respect my request to document methods using @lends unless they have their own individual comments. This is apparently in contradiction with the [example use in the documentation](http://usejsdoc.org/tags-lends.html).

I have source like...

```
_ = require("lodash");

/** @class */
function Thing(){ }

Thing.prototype = _.create(Object.prototype, /** @lends Thing.prototype */ {
    /** Something you can do to a thing. */
    present:function(){
        console.log("This function is rendered in the jsdoc output for Thing");
    },
    absent:function(){
        console.log("This function is suppressed in the jsdoc output for Thing");
    },
})
```

But running `node_modules/.bin/jsdoc example.js && open out/Thing.html` still produces [a file with the 'absent' method completely missing](https://github.com/jsdoc3/jsdoc/files/482306/Thing.html.zip) from the list of available methods, although the 'present' method appears.

Is there a way to force JSDoc to respect the @lends directive, to force methods to appear in the documentation whether or not they yet have a comment? 

Without this feature, a whole lot of boilerplate comments are required. Potential surprising issues from failing to complete this manual step for a newly authored method declaration are likely (methods which are present, but missing from the documentation). At least some classes and methods (and this is always my aspiration) require no commenting because the responsibilities are so clearly implied by the choice of naming and structure, so the failure of @lends to respect this coding style will force code to be less readable (requiring empty comments for items to appear in the documentation).

This seems to have been available and explored in the past (I could find stuff from 2008, and maybe an aspiration for future inclusion) but I can't find any clear documentation how to do it with the latest version of JSDoc. 

Additionally if @lends actively ignores uncommented methods, then this should be noted in the documentation for @lends as I spent a bunch of time trying to figure out what was wrong with my use of @lends, and the answer was apparently nothing, except its strict requirement for there being java-style comments provided for every symbol, (rather defeating the purpose of @lends) .

**Comment by hegemonic** [comment] 2017-02-23 22:11
Duplicate of #1305, which is now fixed. (The docs were indeed incorrect.)

**Closed by hegemonic** 2017-02-23 22:11 UTC
