### ISSUE TITLE
v3.3beta1: @class not parsed properly

### ISSUE THREAD

**Issue by mwittig** [jsdoc3/jsdoc#935] opened 2015-03-02 14:56 UTC
I have the following template which parses fine with JSDoc 3.2:

/**
 * Creates a new instance of MyClass
 * @class
 * Description of MyClass, for example, a longer text describing the MyClass concept
 */
function MyClass() {

}

With JSDoc 3.3 the text following the @class line appears to be interpreted as class name. This is what I can see in the generated class index, al least. If extend the line to "@class MyClass" this does not work as intended, either. 

Here is the relevant output I get from jsDoc -X:

[
    {
        "comment": "/**\r\n * Creates a new instance of MyClass\r\n * @class MyClass\r\n * Description of MyClass, for example, a longer tex
t describing the MyClass concept.\r\n */",
        "meta": {
            "range": [
                0,
                152
            ],
            "filename": "test.js",
            "lineno": 1,
            "path": "C:\\Users\\marcus\\client\\src",
            "code": {}
        },
        "description": "Creates a new instance of MyClass",
        "kind": "class",
        "name": "MyClass\rDescription of MyClass, for example, a longer text describing the MyClass concept.",
        "longname": "MyClass\rDescription of MyClass, for example, a longer text describing the MyClass concept.",
        "scope": "global"
    },
    ...

**Comment by hegemonic** [comment] 2015-03-02 16:47
This is the expected behavior. If you want to provide an extended description of the class, you can do so by adding the `@classdesc` tag before the description.

**Comment by mwittig** [comment] 2015-03-02 17:36
Thank you for your advice, I wasn't aware of this, as earlier version accepted the erroneous markup and produced sensible results through. I'll update my source code documentation accordingly and try again later.

**Comment by hegemonic** [comment] 2015-03-03 22:03
Thanks for clarifying that the same markup worked in previous versions of JSDoc--I missed that in your original report. In that case, I'd prefer to get it working again. I'll go ahead and reopen this issue while I investigate.

**Comment by hegemonic** [comment] 2015-03-05 19:01
Looks like this was caused by f1354563965792b8dd183f5a5331f8fcc67ea319, which fixed #806.

**Comment by hegemonic** [comment] 2015-03-05 23:09
Fixed on master and releases/3.3. Again, thanks for clarifying that this was a regression!

**Closed by hegemonic** 2015-03-05 23:09 UTC
Labels: bugfix
