### ISSUE TITLE
got segmentation fault on jsdoc parsing 

### ISSUE THREAD

**Issue by app3x** [jsdoc3/jsdoc#984] opened 2015-04-14 14:19 UTC
got ```  segmentation fault ``` issue with ``` JSDoc 3.3.0-beta3 ``` on ``` Linux 3.8.0-44 Ubuntu (node v0.10.29)``` or ``` mac os x yosemite (node v0.12.2) ```

**Comment by hegemonic** [comment] 2015-04-16 23:55
Can you please provide a file that I can use to reproduce the problem?

I've heard one report of this issue on Ubuntu, but I haven't heard of it happening on OS X.

**Comment by app3x** [comment] 2015-04-27 15:29
it happens on different files, depends on number of files, what info i cant provide?
i have got more than 900 js files to parse, but only ~50 of them got jsdoc notations

**Comment by hegemonic** [comment] 2015-05-02 00:07
I need a set of files that consistently causes a segfault, so that I can reproduce the issue.

Closing due to lack of information for now. If you can provide a set of files that consistently cause a segfault, I'll reopen.

**Closed by hegemonic** 2015-05-02 00:07 UTC
Labels: needmoreinfo, waiting

**Comment by muhammad-saleh** [comment] 2015-05-13 22:29
Guys, I faced the same issue on OS X Yosemite
I'm sorry I can't post the code
But the weird thing is that it happens when I run:
``
jsdoc -c conf.json
``

And not:
``
jsdoc -r ./source/assets/js -d Documentation
``

Here's my conf.json:
``
{
    "tags": {
        "allowUnknownTags": true
    },
    "source": {
        "include": "./source/assets/js",
        "exclude": ["./source/assets/js/_angular-core"]
    },
    "plugins": [],
    "opts": {
        "destination": "Documentation",
        "recurse": true
    }
}
``

**Comment by muhammad-saleh** [comment] 2015-05-24 09:03
I've noticed something:
I was able to fix the segmentation fault issue only after adding a very specific folder to the exclude array in conf.json
So for anyone facing a similar issue please try to add folders one by one in the exclude array

**Comment by app3x** [comment] 2015-05-24 17:27
looks like it happens with large amount of js files

**Comment by muhammad-saleh** [comment] 2015-05-24 17:29
Well, the weird thing is the folder which was causing the problem only had something like 3 or 4 files but it had another folder inside !
And if I excluded another folders with larger number of files the problem is still there
So I don't know maybe the nested folders causing the problem ?

**Comment by buzzzzer** [comment] 2015-05-25 05:20
What is the full path to folder that is causing the problem?

**Comment by muhammad-saleh** [comment] 2015-05-25 07:42
Folder Path:
``
/Users/mohamedsaleh/Projects/xxxxx/02_build/xxxxx-source/source/assets/js/_local/
``

Internal folder structure for the folder _local :
``
- localfolder
        _localfile.js
        _taf.js
- xx-legacy.js
- _config.js
``
