### ISSUE TITLE
Not all members are documented when using @extends or @implements

### ISSUE THREAD

**Issue by pnstickne** [jsdoc3/jsdoc#934] opened 2015-03-01 05:41 UTC
When a class extends another class (noticed with multiple `@extends`) then _some_ but _not all_ of the members in the source class are picked up / rendered in the extending type.

The same problem exists for `@implements/@interface`. _Some_ but _not all_ of the members are displayed in the documentation for the target type.

There isn't a readily [to me] apparent pattern - in some cases "maybe 1 in 3" are omitted.

The documentation for the source class (when using `@class/@extends`) correctly contains all the members. (For some reason `@interface` isn't generating HTML documentation files at all.. although the type is linked correctly and one can "view the interface source" in the `@implements` target; at least _when_ the members are shown...)

Both JSDoc 3.3.0-alpha13 and JSDoc 3.3.0-beta1 have the same problem.

**Comment by pnstickne** [comment] 2015-03-01 06:34
Changing the member name on the `@class` being `@extended` "makes it appear" in the target .. not sure what the name-change requirement is though.

**Comment by pnstickne** [comment] 2015-03-01 06:42
Changing the member name (in the class being implemented/extended) appears to "fix" the problem.

(However, I cannot find another base implementation of the problematic names - and some names are "ok" even though they are no more or less distinct.)

**Comment by hegemonic** [comment] 2015-03-02 01:37
@pnstickne This is a lot of useful information, but I'm not able to reproduce the issue. Can you provide an example that demonstrates the problem? (A simplified test case would be ideal, but pointing me towards some actual source files would be okay too.)

**Comment by pnstickne** [comment] 2015-03-02 04:44
Find an example is .. problematic.

I'm going to have to do a full deconstruct (when I was playing with it today I was only able to verify the problem when using "N" for some value of N number of extends..)

This issue does indeed need a test-case I can hand off and I'll work on getting better data when I have time.

**Comment by hegemonic** [comment] 2015-03-03 22:06
@pnstickne Thanks, much appreciated. I'll keep this issue open while you investigate.

**Comment by hegemonic** [comment] 2015-03-20 00:28
@pnstickne Any luck coming up with an example that I can use to reproduce this issue?

**Comment by hegemonic** [comment] 2015-04-10 23:30
Closing due to lack of information.

**Closed by hegemonic** 2015-04-10 23:30 UTC
Labels: needmoreinfo, waiting
