### ISSUE TITLE
Why must i always define the full path "module:moduleA.classA" even when i reference to a part of its own module?

### ISSUE THREAD

**Issue by conzul** [jsdoc3/jsdoc#1148] opened 2016-01-19 10:10 UTC
Its really annoying to always define the module:moduleA even when i am in my own module.
When i do not do that - no links to its own members are generated in this module :-(

Its fine to use the full path for dependency modules.

This is a example code for documenting my javascript custom modules:

```javascript
mynamespace.module("mynamespace.moduleA", ["mynamespace.moduleB"], function (moduleB) {
    "use strict";

    // Save dependency references for faster access
    var myCustomSort = moduleB.myCustomSort;

    /**
     * My awesome module A
     * @module moduleA
     */

/**
 * Clamps the given value into the given min/max range
 * @memberOf module:moduleA
 * @param value {number} Input value
 * @param min {number} Min value
 * @param max {number} Max value
 * @returns {number}
 */
function clamp(value, min, max) {
    return Math.max(Math.min(value, max), min);
}

/**
 * My enumeration
 * @memberOf module:moduleA
 * @enum {number}
 */
var MyEnumeration = {
    /** A */
    A: 0,
    /** B */
    B: 1,
    /** C */
    C: 2,
};

/**
 * My class A
 * @memberOf module:moduleA
 * @param data {Array} Data values
 * @param type {module:moduleA.MyEnumeration} Class type
 * @constructor
 */
function MyClassA(data, type) {
    /** @property {module:moduleA.MyEnumeration} Class type */
    this.type = type;
    /** @property {Array} Some random data passed */
    this.data = data;
}

/**
 * <p>Adds a dependency key to the list if not exists</p>
 * <p>Does sorts the data values using {@link module:moduleB.myCustomSort}</p>
 * <p>Returns itself {@link module:moduleA.MyClassA} to support chaining</p>
 * @param value {string} Value item
 * @returns {MyClassA}
 */
MyClassA.prototype.insertData = function (value) {
    this.data.push(value);

    // Sort data using moduleB awesome sort function
    myCustomSort(this.data);

    return this;
};

return {
    clamp: clamp,
    MyClassA: MyClassA,
    MyEnumeration: MyEnumeration
};
});
```

**Comment by motet-a** [comment] 2016-08-28 06:44
:+1: 

Is not there any way to write something shorter? `module:my-module~fooBar` is really verbous.

**Comment by seansd** [comment] 2016-08-28 18:57
That's no different then classes or namespaces. . . you can write it in a different way like @memberOf or @lends, but since JavaScript doesn't have types (beyond primitives), and you can always do parasitic or prototypical inheritance, there's no way for an engine to know how to interpret the psuedo type/property/method.

The only thing I can think of would be to add a 2nd tag that's kinda like a "with" statement in JS that forces all types to automatically be a child of some parent. . . .

**Comment by hegemonic** [comment] 2016-08-31 00:29
This is effectively a duplicate of #101.

**Closed by hegemonic** 2016-08-31 00:29 UTC
