### ISSUE TITLE
Inheritance and "this"

### ISSUE THREAD

**Issue by Raptor399** [jsdoc3/jsdoc#859] opened 2014-12-31 14:21 UTC
In pull request #829 the access parameter "public" is being introduced. In testing this functionality I encountered unexpected behaviour. I tried to capture the behaviour in a spec that I added in my branch https://github.com/Raptor399/jsdoc/tree/inheritance-test in commit Raptor399/jsdoc@7e53c5ec4cad360923e707bb5edcfe48535129fa .

Sorry for the AMD fixture, I wanted to stick close to my local setup in this test.

When I run `gulp test`, three errors surface:

```
  1) When a symbol inherits a member marked private it does not exist
  Message:
    Expected { comment : '/**
     * Not referenced with "this.prop1".
     * @private
     */', meta : { range : [ 335, 346 ], filename : '[[string0]]', lineno : 17, path : 'null', code : { id : 'astnode100002467', name : 'prop1', type : 'Literal', value : 'null' } }, description : 'Not referenced with "this.prop1".', access : 'private', name : 'prop1', longname : 'Gnat#prop1', kind : 'member', memberof : 'Gnat', scope : 'instance', inherits : 'Gnu#prop1', inherited : true, postProcess : Function, addTag : Function, setMemberof : Function, setLongname : Function, setScope : Function, borrow : Function, mix : Function, augment : Function, setMeta : Function } to be undefined.
  Stacktrace:
    undefined

  2) When a symbol inherits a member marked private overwritten with "this" it does not exist
  Message:
    Expected { comment : '', meta : { range : [ 845, 861 ], filename : '[[string0]]', lineno : 43, path : 'null', code : { id : 'astnode100002480', name : 'this.prop2', type : 'Identifier', value : 'val', paramnames : [  ] } }, undocumented : true, name : 'prop2', longname : 'Gnat#prop2', kind : 'member', memberof : 'Gnat', scope : 'instance', inherits : 'Gnu#prop2', inherited : true, postProcess : Function, addTag : Function, setMemberof : Function, setLongname : Function, setScope : Function, borrow : Function, mix : Function, augment : Function, setMeta : Function } to be undefined.
  Stacktrace:
    undefined

  3) When a symbol inherits a member marked public overwritten with "this" it exists and is public
  Message:
    Expected undefined to be 'public'.
  Stacktrace:
    undefined
```

This appears to indicate two issues:

* Members marked as `@private` are inherited nonetheless. I know Javascript does not hide inherited members, but maybe the documentation should hide them. Sounds a bit contradictory to inherit private stuff?

* Whether members are marked as `@private` or `@public`, referencing them with "this" appears to reset their access to `undefined`. I don't think this should happen. If a member is known already, referencing it should respect its access.

**Comment by Raptor399** [comment] 2015-01-02 11:52
> > * Members marked as `@private` are inherited nonetheless. I know Javascript does not hide inherited members, but maybe the documentation should hide them. Sounds a bit contradictory to inherit private stuff?
>
> I think it's appropriate that they're inherited, but I also think the inherited symbols should be marked as private (which would prevent them from appearing in the docs). Is that the case?

Yep, that is the case. Judging by the test output `access: 'private'` is inherited:
```
  1) When a symbol inherits a member marked private it does not exist
  Message:
    Expected { comment : '/**
     * Not referenced with "this.prop1".
     * @private
     */', meta : { range : [ 335, 346 ], filename : '[[string0]]', lineno : 17, path : 'null', code : { id : 'astnode100002467', name : 'prop1', type : 'Literal', value : 'null' } }, description : 'Not referenced with "this.prop1".', access : 'private', name : 'prop1', longname : 'Gnat#prop1', kind : 'member', memberof : 'Gnat', scope : 'instance', inherits : 'Gnu#prop1', inherited : true, postProcess : Function, addTag : Function, setMemberof : Function, setLongname : Function, setScope : Function, borrow : Function, mix : Function, augment : Function, setMeta : Function } to be undefined.
  Stacktrace:
    undefined
```
So that particular spec is incorrect and should be "When a symbol inherits a member marked private it is private".

**Comment by hegemonic** [comment] 2015-01-04 20:15
@Raptor399 I took a look at this, and it appears that everything is working as intended.

I tested with this cut-down version of your original test fixture:

```js
/**
 * @exports Gnu
 */
define(["dojo/_base/declare"], function(declare) {
  /**
   * @class Gnu
   */
  return declare("Gnu", null,
    /** @lends Gnu.prototype */
    {
    /**
     * Referenced with "this.prop1".
     * @private
     */
    prop1: null,

    /**
     * Some gnu function that sets "this.prop1".
     * @param val Value to set
     */
    setProps: function(val) {
      // Reference existing member.
      this.prop1 = val;
    }
  });
});
```

I ran `jsdoc -X` to get a JSON version of the parse results. In the parse results, I saw two doclets for `Gnu#prop1`:

1. Generated by the first reference to `Gnu#prop1`, which has a JSDoc comment. This doclet has the `description` property set to `Referenced with "this.prop1".` and the `access` property set to `private`.
2. Generated by the second reference to `Gnu#prop1`, which does not have a JSDoc comment. This doclet has the `undocumented` property set to `true`, which causes JSDoc to discard the doclet before it generates any output.

So, in practice, only doclet 1 (the one marked `private`) is used to generate docs.

If you look at all the test specs for JSDoc tags, you'll see that a number of them (for example, the [`borrows` spec](https://github.com/jsdoc3/jsdoc/blob/master/test/specs/tags/borrowstag.js) include code to filter out undocumented doclets, which addresses exactly this issue.

Closing this issue based on the above. If I misunderstood something, please let me know, and I'll be happy to reopen the issue.

**Closed by hegemonic** 2015-01-04 20:15 UTC
Labels: bugfix

**Comment by Raptor399** [comment] 2015-01-05 10:00
@hegemonic Thank you for taking the time to dive into this and jotting down the explanation. And sorry for the wild goose chase!
