### ISSUE TITLE
Document array elements by index

### ISSUE THREAD

**Issue by jeron-diovis** [jsdoc3/jsdoc#1295] opened 2016-11-24 22:42 UTC
Let say I have an a function parameter, which is always an array of two elements, first is a Function and second is a String. How can I document such parameter?

---

I tried this:
```js
/**
* @param {Array.<Function, String>} my_param
*/
```

It does not work. It seems that jsdoc just uses the last type inside `<...>` – because autocompletion (in WebStorms in my case) for `my_param[1].c` shows me `charAt`, and if I swap types in declaration, it shows `call`.

---

I tried this:
```js
/**
* @typedef MyArray
* @property {Function} 0
* @property {String} 1
*
* @param {MyArray} my_param
*/
```

It does not work, because numbers seems aren't treated as prop names at all.

---

I tried this:
```js
/**
* @typedef {{ 0: Function, 1: String }} MyArray
*
* @param {MyArray} my_param
*/
```

It seems to be just the same as previous one. If I use non-numeric names, it works just fine.

Also, it's interesting, that for `foo.bar` hinting works, but for `foo['bar']` it doesn't.

---

So, is there any way to do this, or will it be added some time? And, if not, then why?

**Comment by dandv** [comment] 2017-06-12 06:21
:+1: I want to document the return type of a function that returns an array of two values. Think something like

```js
/**
 * @param ...
 * @returns {Array<[Number, Number]>} The quotient and the remainder
 */
function bigIntDivision(a, b) { ... }

const [quotient, remainder] = bigIntDivision(a, b);
```

**Comment by dandv** [comment] 2017-06-12 06:26
Related: #1073

**Comment by hegemonic** [comment] 2017-07-02 23:47
Duplicate of #1073.

**Closed by hegemonic** 2017-07-02 23:47 UTC
