### ISSUE TITLE
class with constructor marked @private is ignored

### ISSUE THREAD

**Issue by myphysicslab** [jsdoc3/jsdoc#958] opened 2015-03-19 04:35 UTC
A common pattern for a utility class is to have a @private constructor (so that no instance can be made) and public static methods.  JSDoc decides to not show the entire class in this case (when --access is set to not include private).

Additionally, the @classdesc needs to still appear for such a class, even though the constructor itself should not appear (when private access is turned off).

My current workaround is to not mark the constructor with @private, and make the body of the constructor just throw an exception.  But when reading the documentation it now looks like you can instantiate these classes.  I can add a description explaining this, or add a @throws tag to the constructor, but far better is to just not show the constructor.

**Comment by myphysicslab** [comment] 2015-03-19 10:43
FYI, adding a @throws tag to the constructor is looking like a good enough workaround for me -- plus it allows the @classdesc to appear (and other tags like @todo, @author).

**Comment by hegemonic** [comment] 2015-03-19 18:12
Duplicate of #952.

**Closed by hegemonic** 2015-03-19 18:12 UTC
