### ISSUE TITLE
Link to external using a quoted value doesn't resolve correctly

### ISSUE THREAD

**Issue by yaronyg** [jsdoc3/jsdoc#1099] opened 2015-10-28 23:14 UTC
I define:

```Javascript
/**
 * @external "bar('Connect')"
 */

/**
 * @function external:"bar('Connect')".callNative
 */

/**
 * Please see {@link external:"bar('Connect')".callNative}
 * @public
 * @function foo
 */
```

__Good News:__ Externals will show a member "bar('Connect')" that will show a member method "callNative()".
__Bad News:__ As shown below, the link in Foo to bar's callNative method will not create a HREF.

```HTML
<p>Please see external:bar('Connect').callNative</p>
```

One solution I tried was:

```Javascript
/**
 * @external bar('Connect')
 */

/**
 * @function external:bar('Connect').callNative
 */

/**
 * Please see {@link external:bar('Connect').callNative}
 * @public
 * @function foo
 */
```

In other words, just omit the quotes.

__Bad News:__ Instead of bar('Connect') being listed in externals on the home page, only bar is listed. If you click on the bar link it won't show callNative. If you click on the foo link the good news is that there is a HREF there! The bad news is, the HREF is broken, clicking on it brings up a File not found error. See below.

```HTML
Please see <a href="external-bar.html#.callNative">external:bar('Connect').callNative</a>
```

How do I fix it so that I can both see bar('Connect') fully listed out as in the first example and be able to link to the callNative method?

Thanks!

**Comment by yaronyg** [comment] 2015-11-11 00:04
Note that I am using the markdown plugin, I wonder if #1035 is relevant here?

**Comment by hegemonic** [comment] 2015-12-09 00:00
After doing a quick test, I'm pretty confident that this is a duplicate of #1035.

**Closed by hegemonic** 2015-12-09 00:00 UTC
