### ISSUE TITLE
Functions as a namespace

### ISSUE THREAD

**Issue by Cortys** [jsdoc3/jsdoc#1115] opened 2015-11-23 22:35 UTC
Is it possible to document a namespace, which is also a function?

When doing something like
```js
/**
 * Does things.
 * @namespace
 * @param {string} name - A name.
 * @return {string} Result.
 */
function test(name) {
    return "Hello " + name + "!";
}

Object.assign(test, {
    /**
     * Another feature.
     * @memberof test
     * @return {number} The time.
     */
    anotherFeature() {
        return Date.now();
    }
});
```

the `test()` function is treated like an object in jsdoc exports (parameters and return are not documented). Is there a way to document such a structure?

**Comment by hegemonic** [comment] 2015-11-25 23:41
Duplicate of #955. Sorry, but there's not a great way to deal with this case right now.

**Closed by hegemonic** 2015-11-25 23:41 UTC
