### ISSUE TITLE
missing module, missing string

### ISSUE THREAD

**Issue by jzakula** [jsdoc3/jsdoc#983] opened 2015-04-13 20:03 UTC
I'm new to JSDoc. I'm just basically trying to get it to run barebones from the command prompt without any options except what may be in the default config.json. I've tried 3 versions. Version 3.3.0 seems unable to find a module. The other seem to be choking on a string in one of the files to be parsed. 

I ran all 3 versions in debug mode and recorded the results which I am including. I am using the JSDoc folder as the working directory as you will see in the prompt. The folder names in the prompts also indicate the version of JSDoc producing the debug output.

I have tried doing a single javascript file as suggested in the readme file. Running in debug mode simply produces no output. In run mode the same errors occur. 

Version 3.3.0-beta3 cannot find the underscore-contrib module though it is in the jsdoc\node-modules folder. (However, according to the readme, jsdoc should not be expecting it because I am not running it via nodejs.)

The other 2 versions seem to be failing because they cannot find a string they expect. This, again, seems at first blush to be an internal

As I said, I am new to JSDoc, and I would expect that others are not running into these errors because I don't see them reported. So I am not sure this is a bug. It could be something else, but I am not sure. Is this really supposed to be linux-only software?  (I am using Windows 7 SP1.) Is it a pathing issue? Is it a JSDoc-Windows only problem? Does the Rhino/java version make a difference? (I am running java 8 update 31. The Rhino is bundled with JSDoc, and I have no classpath environment variable so there is no Rhino conflict there.)  

Or maybe it is a couple of bugs. If there is anything else I can send, please let me know. I would really like to get this to work if I can.

Thanks,

C:\Users\jzakula3\IdeaProjects\jsdoc-3.3.0-beta3>jsdoc.cmd C:\Users\jzakula3\IdeaProjects\kodaraemailparsers\src\com\kodaris\commerce\parsing --debug -r
DEBUG: JSDoc 3.3.0-beta3 (Wed, 18 Mar 2015 16:44:14 GMT)
DEBUG: Environment info: {
"env": {
"conf": {
"tags": {
"allowUnknownTags": true,
"dictionaries": [
"jsdoc",
"closure"
]
},
"templates": {
"monospaceLinks": false,
"cleverLinks": false,
"default": {
"outputSourceFiles": true
}
},
"source": {
"includePattern": ".+\.js(doc)?$",
"excludePattern": "(^|\/|\\)"
},
"plugins": []
},
"opts": {
"": [
"C:\Users\jzakula3\IdeaProjects\kodaraemailparsers\src\com\kodaris\commerce\parsing"
],
"debug": true,
"recurse": true,
"destination": "./out/",
"encoding": "utf8"
}
}
}
java.lang.Exception: Error: Module "underscore-contrib" not found.
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.mozilla.javascript.MemberBox.newInstance(MemberBox.java:159)
at org.mozilla.javascript.NativeJavaClass.constructInternal(NativeJavaClass.java:266)
at org.mozilla.javascript.NativeJavaClass.constructSpecific(NativeJavaClass.java:205)
at org.mozilla.javascript.NativeJavaClass.construct(NativeJavaClass.java:166)
at org.mozilla.javascript.ScriptRuntime.newObject(ScriptRuntime.java:2348)
at org.mozilla.javascript.gen.file__C__Users_jzakula3_IdeaProjects_jsdoc_3_3_0_beta3_rhino_rhino_shim_js_4._c_trace_15(Unknown Source)
at org.mozilla.javascript.gen.file__C__Users_jzakula3_IdeaProjects_jsdoc_3_3_0_beta3_rhino_rhino_shim_js_4.call(Unknown Source)
at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
at org.mozilla.javascript.gen.file__C__Users_jzakula3_IdeaProjects_jsdoc_3_3_0_beta3_jsdoc_js_1._c_anonymous_3(Unknown Source)
at org.mozilla.javascript.gen.file__C__Users_jzakula3_IdeaProjects_jsdoc_3_3_0_beta3_jsdoc_js_1.call(Unknown Source)
at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23)
at org.mozilla.javascript.gen.file__C__Users_jzakula3_IdeaProjects_jsdoc_3_3_0_beta3_jsdoc_js_1._c_script_0(Unknown Source)
at org.mozilla.javascript.gen.file__C__Users_jzakula3_IdeaProjects_jsdoc_3_3_0_beta3_jsdoc_js_1.call(Unknown Source)
at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3090)
at org.mozilla.javascript.gen.file__C__Users_jzakula3_IdeaProjects_jsdoc_3_3_0_beta3_jsdoc_js_1.call(Unknown Source)
at org.mozilla.javascript.gen.file__C__Users_jzakula3_IdeaProjects_jsdoc_3_3_0_beta3_jsdoc_js_1.exec(Unknown Source)
at org.mozilla.javascript.commonjs.module.Require.executeModuleScript(Require.java:355)
at org.mozilla.javascript.commonjs.module.Require.getExportedModuleInterface(Require.java:288)
at org.mozilla.javascript.commonjs.module.Require.requireMain(Require.java:137)
at org.mozilla.javascript.tools.shell.Main.processSource(Main.java:525)
at org.mozilla.javascript.tools.shell.Main.processFiles(Main.java:176)
at org.mozilla.javascript.tools.shell.Main$IProxy.run(Main.java:100)
at org.mozilla.javascript.Context.call(Context.java:489)
at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:504)
at org.mozilla.javascript.tools.shell.Main.exec(Main.java:158)
at org.mozilla.javascript.tools.shell.Main.main(Main.java:136)

C:\Users\jzakula3\IdeaProjects\jsdoc-3.3.0-alpha13>jsdoc.cmd C:\Users\jzakula3\IdeaProjects\kodaraemailparsers\src\com\kodaris\commerce\parsing --debug -r
DEBUG: JSDoc 3.3.0-alpha13 (Tue, 23 Dec 2014 23:21:32 GMT)
DEBUG: Environment info: {
"env": {
"conf": {
"tags": {
"allowUnknownTags": true,
"dictionaries": [
"jsdoc",
"closure"
]
},
"templates": {
"monospaceLinks": false,
"cleverLinks": false,
"default": {
"outputSourceFiles": true
}
},
"source": {
"includePattern": ".+\.js(doc)?$",
"excludePattern": "(^|\/|\\)"
},
"plugins": []
},
"opts": {
"": [
"C:\Users\jzakula3\IdeaProjects\kodaraemailparsers\src\com\kodaris\commerce\parsing"
],
"debug": true,
"recurse": true,
"destination": "./out/",
"encoding": "utf8"
}
}
}
DEBUG: Parsing source files: [
"C:\Users\jzakula3\IdeaProjects\kodaraemailparsers\src\com\kodaris\commerce\parsing\Amer_Tonneau_Appl_parser.js",
"C:\Users\jzakula3\IdeaProjects\kodaraemailparsers\src\com\kodaris\commerce\parsing\app.js",
"C:\Users\jzakula3\IdeaProjects\kodaraemailparsers\src\com\kodaris\commerce\parsing\CustomerCsvParser.js",
"C:\Users\jzakula3\IdeaProjects\kodaraemailparsers\src\com\kodaris\commerce\parsing\GenericTransactionParser.js",
"C:\Users\jzakula3\IdeaProjects\kodaraemailparsers\src\com\kodaris\commerce\parsing\jsLib\kParse.js",
"C:\Users\jzakula3\IdeaProjects\kodaraemailparsers\src\com\kodaris\commerce\parsing\jsLib\kParse_copy.js",
"C:\Users\jzakula3\IdeaProjects\kodaraemailparsers\src\com\kodaris\commerce\parsing\jsLib\lodash.js",
"C:\Users\jzakula3\IdeaProjects\kodaraemailparsers\src\com\kodaris\commerce\parsing\jsLib\PdfToText.js",
"C:\Users\jzakula3\IdeaProjects\kodaraemailparsers\src\com\kodaris\commerce\parsing\kParseTest.js",
"C:\Users\jzakula3\IdeaProjects\kodaraemailparsers\src\com\kodaris\commerce\parsing\ParsePOFromPDF.js",
"C:\Users\jzakula3\IdeaProjects\kodaraemailparsers\src\com\kodaris\commerce\parsing\ParsePOFromPdf_Dummy.js",
"C:\Users\jzakula3\IdeaProjects\kodaraemailparsers\src\com\kodaris\commerce\parsing\pdfParsers\basicPDFParser.js",
"C:\Users\jzakula3\IdeaProjects\kodaraemailparsers\src\com\kodaris\commerce\parsing\TrendPOParser.js"
]
Parsing C:\Users\jzakula3\IdeaProjects\kodaraemailparsers\src\com\kodaris\commerce\parsing\Amer_Tonneau_Appl_parser.js ...complete.
Parsing C:\Users\jzakula3\IdeaProjects\kodaraemailparsers\src\com\kodaris\commerce\parsing\app.js ...complete.
Parsing C:\Users\jzakula3\IdeaProjects\kodaraemailparsers\src\com\kodaris\commerce\parsing\CustomerCsvParser.js ...complete.
Parsing C:\Users\jzakula3\IdeaProjects\kodaraemailparsers\src\com\kodaris\commerce\parsing\GenericTransactionParser.js ...complete.
Parsing C:\Users\jzakula3\IdeaProjects\kodaraemailparsers\src\com\kodaris\commerce\parsing\jsLib\kParse.js ...org.mozilla.javascript.WrappedException: Wrapped java.lang.StringIndexOutOfBoundsException: String index out of range: -2
at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1754)
at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148)
at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
at org.mozilla.javascript.gen.file__C__Users_jzakula3_IdeaProjects_jsdoc_3_3_0_alpha13_rhino_jsdoc_src_astbuilder_js_64._c_anonymous_2(Unknown Source)
at org.mozilla.javascript.gen.file__C__Users_jzakula3_IdeaProjects_jsdoc_3_3_0_alpha13_rhino_jsdoc_src_astbuilder_js_64.call(Unknown Source)
at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
at org.mozilla.javascript.gen.file__C__Users_jzakula3_IdeaProjects_jsdoc_3_3_0_alpha13_lib_jsdoc_src_parser_js_61._c_anonymous_14(Unknown Source)
at org.mozilla.javascript.gen.file__C__Users_jzakula3_IdeaProjects_jsdoc_3_3_0_alpha13_lib_jsdoc_src_parser_js_61.call(Unknown Source)
at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
at org.mozilla.javascript.gen.file__C__Users_jzakula3_IdeaProjects_jsdoc_3_3_0_alpha13_lib_jsdoc_src_parser_js_61._c_anonymous_7(Unknown Source)
at org.mozilla.javascript.gen.file__C__Users_jzakula3_IdeaProjects_jsdoc_3_3_0_alpha13_lib_jsdoc_src_parser_js_61.call(Unknown Source)
at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
at org.mozilla.javascript.gen.file__C__Users_jzakula3_IdeaProjects_jsdoc_3_3_0_alpha13_cli_js_19._c_anonymous_24(Unknown Source)
at org.mozilla.javascript.gen.file__C__Users_jzakula3_IdeaProjects_jsdoc_3_3_0_alpha13_cli_js_19.call(Unknown Source)
at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:85)
at org.mozilla.javascript.gen.file__C__Users_jzakula3_IdeaProjects_jsdoc_3_3_0_alpha13_cli_js_19._c_anonymous_17(Unknown Source)
at org.mozilla.javascript.gen.file__C__Users_jzakula3_IdeaProjects_jsdoc_3_3_0_alpha13_cli_js_19.call(Unknown Source)
at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
at org.mozilla.javascript.gen.file__C__Users_jzakula3_IdeaProjects_jsdoc_3_3_0_alpha13_cli_js_19._c_anonymous_10(Unknown Source)
at org.mozilla.javascript.gen.file__C__Users_jzakula3_IdeaProjects_jsdoc_3_3_0_alpha13_cli_js_19.call(Unknown Source)
at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
at org.mozilla.javascript.gen.file__C__Users_jzakula3_IdeaProjects_jsdoc_3_3_0_alpha13_jsdoc_js_1._c_anonymous_3(Unknown Source)
at org.mozilla.javascript.gen.file__C__Users_jzakula3_IdeaProjects_jsdoc_3_3_0_alpha13_jsdoc_js_1.call(Unknown Source)
at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23)
at org.mozilla.javascript.gen.file__C__Users_jzakula3_IdeaProjects_jsdoc_3_3_0_alpha13_jsdoc_js_1._c_script_0(Unknown Source)
at org.mozilla.javascript.gen.file__C__Users_jzakula3_IdeaProjects_jsdoc_3_3_0_alpha13_jsdoc_js_1.call(Unknown Source)
at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3090)
at org.mozilla.javascript.gen.file__C__Users_jzakula3_IdeaProjects_jsdoc_3_3_0_alpha13_jsdoc_js_1.call(Unknown Source)
at org.mozilla.javascript.gen.file__C__Users_jzakula3_IdeaProjects_jsdoc_3_3_0_alpha13_jsdoc_js_1.exec(Unknown Source)
at org.mozilla.javascript.commonjs.module.Require.executeModuleScript(Require.java:355)
at org.mozilla.javascript.commonjs.module.Require.getExportedModuleInterface(Require.java:288)
at org.mozilla.javascript.commonjs.module.Require.requireMain(Require.java:137)
at org.mozilla.javascript.tools.shell.Main.processSource(Main.java:525)
at org.mozilla.javascript.tools.shell.Main.processFiles(Main.java:176)
at org.mozilla.javascript.tools.shell.Main$IProxy.run(Main.java:100)
at org.mozilla.javascript.Context.call(Context.java:489)
at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:504)
at org.mozilla.javascript.tools.shell.Main.exec(Main.java:158)
at org.mozilla.javascript.tools.shell.Main.main(Main.java:136)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -2
at java.lang.String.substring(Unknown Source)
at org.jsdoc.AstBuilder.processComment(AstBuilder.java:603)
at org.jsdoc.AstBuilder.processNode(AstBuilder.java:394)
at org.jsdoc.AstBuilder.access$000(AstBuilder.java:32)
at org.jsdoc.AstBuilder$1.visit(AstBuilder.java:311)
at org.mozilla.javascript.ast.AstRoot.visitComments(AstRoot.java:97)
at org.jsdoc.AstBuilder.processAllComments(AstBuilder.java:319)
at org.jsdoc.AstBuilder.build(AstBuilder.java:138)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
... 39 more
undefined

C:\Users\jzakula3\IdeaProjects\jsdoc-3.3.0-alpha13>jsdoc.cmd C:\Users\jzakula3\IdeaProjects\kodaraemailparsers\src\com\kodaris\commerce\parsing --debug -r
DEBUG: JSDoc 3.3.0-alpha13 (Tue, 23 Dec 2014 23:21:32 GMT)
DEBUG: Environment info: {
"env": {
"conf": {
"tags": {
"allowUnknownTags": true,
"dictionaries": [
"jsdoc",
"closure"
]
},
"templates": {
"monospaceLinks": false,
"cleverLinks": false,
"default": {
"outputSourceFiles": true
}
},
"source": {
"includePattern": ".+\.js(doc)?$",
"excludePattern": "(^|\/|\\)"
},
"plugins": []
},
"opts": {
"": [
"C:\Users\jzakula3\IdeaProjects\kodaraemailparsers\src\com\kodaris\commerce\parsing"
],
"debug": true,
"recurse": true,
"destination": "./out/",
"encoding": "utf8"
}
}
}
DEBUG: Parsing source files: [
"C:\Users\jzakula3\IdeaProjects\kodaraemailparsers\src\com\kodaris\commerce\parsing\Amer_Tonneau_Appl_parser.js",
"C:\Users\jzakula3\IdeaProjects\kodaraemailparsers\src\com\kodaris\commerce\parsing\app.js",
"C:\Users\jzakula3\IdeaProjects\kodaraemailparsers\src\com\kodaris\commerce\parsing\CustomerCsvParser.js",
"C:\Users\jzakula3\IdeaProjects\kodaraemailparsers\src\com\kodaris\commerce\parsing\GenericTransactionParser.js",
"C:\Users\jzakula3\IdeaProjects\kodaraemailparsers\src\com\kodaris\commerce\parsing\jsLib\kParse.js",
"C:\Users\jzakula3\IdeaProjects\kodaraemailparsers\src\com\kodaris\commerce\parsing\jsLib\lodash.js",
"C:\Users\jzakula3\IdeaProjects\kodaraemailparsers\src\com\kodaris\commerce\parsing\jsLib\PdfToText.js",
"C:\Users\jzakula3\IdeaProjects\kodaraemailparsers\src\com\kodaris\commerce\parsing\kParseTest.js",
"C:\Users\jzakula3\IdeaProjects\kodaraemailparsers\src\com\kodaris\commerce\parsing\ParsePOFromPDF.js",
"C:\Users\jzakula3\IdeaProjects\kodaraemailparsers\src\com\kodaris\commerce\parsing\ParsePOFromPdf_Dummy.js",
"C:\Users\jzakula3\IdeaProjects\kodaraemailparsers\src\com\kodaris\commerce\parsing\pdfParsers\basicPDFParser.js",
"C:\Users\jzakula3\IdeaProjects\kodaraemailparsers\src\com\kodaris\commerce\parsing\TrendPOParser.js"
]
Parsing C:\Users\jzakula3\IdeaProjects\kodaraemailparsers\src\com\kodaris\commerce\parsing\Amer_Tonneau_Appl_parser.js ...complete.
Parsing C:\Users\jzakula3\IdeaProjects\kodaraemailparsers\src\com\kodaris\commerce\parsing\app.js ...complete.
Parsing C:\Users\jzakula3\IdeaProjects\kodaraemailparsers\src\com\kodaris\commerce\parsing\CustomerCsvParser.js ...complete.
Parsing C:\Users\jzakula3\IdeaProjects\kodaraemailparsers\src\com\kodaris\commerce\parsing\GenericTransactionParser.js ...complete.
Parsing C:\Users\jzakula3\IdeaProjects\kodaraemailparsers\src\com\kodaris\commerce\parsing\jsLib\kParse.js ...complete.
Parsing C:\Users\jzakula3\IdeaProjects\kodaraemailparsers\src\com\kodaris\commerce\parsing\jsLib\lodash.js ...org.mozilla.javascript.WrappedException: Wrapped java.lang.StringIndexOutOfBoundsException: String index out of range: -2
at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1754)
at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148)
at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
at org.mozilla.javascript.gen.file__C__Users_jzakula3_IdeaProjects_jsdoc_3_3_0_alpha13_rhino_jsdoc_src_astbuilder_js_64._c_anonymous_2(Unknown Source)
at org.mozilla.javascript.gen.file__C__Users_jzakula3_IdeaProjects_jsdoc_3_3_0_alpha13_rhino_jsdoc_src_astbuilder_js_64.call(Unknown Source)
at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
at org.mozilla.javascript.gen.file__C__Users_jzakula3_IdeaProjects_jsdoc_3_3_0_alpha13_lib_jsdoc_src_parser_js_61._c_anonymous_14(Unknown Source)
at org.mozilla.javascript.gen.file__C__Users_jzakula3_IdeaProjects_jsdoc_3_3_0_alpha13_lib_jsdoc_src_parser_js_61.call(Unknown Source)
at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
at org.mozilla.javascript.gen.file__C__Users_jzakula3_IdeaProjects_jsdoc_3_3_0_alpha13_lib_jsdoc_src_parser_js_61._c_anonymous_7(Unknown Source)
at org.mozilla.javascript.gen.file__C__Users_jzakula3_IdeaProjects_jsdoc_3_3_0_alpha13_lib_jsdoc_src_parser_js_61.call(Unknown Source)
at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
at org.mozilla.javascript.gen.file__C__Users_jzakula3_IdeaProjects_jsdoc_3_3_0_alpha13_cli_js_19._c_anonymous_24(Unknown Source)
at org.mozilla.javascript.gen.file__C__Users_jzakula3_IdeaProjects_jsdoc_3_3_0_alpha13_cli_js_19.call(Unknown Source)
at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:85)
at org.mozilla.javascript.gen.file__C__Users_jzakula3_IdeaProjects_jsdoc_3_3_0_alpha13_cli_js_19._c_anonymous_17(Unknown Source)
at org.mozilla.javascript.gen.file__C__Users_jzakula3_IdeaProjects_jsdoc_3_3_0_alpha13_cli_js_19.call(Unknown Source)
at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
at org.mozilla.javascript.gen.file__C__Users_jzakula3_IdeaProjects_jsdoc_3_3_0_alpha13_cli_js_19._c_anonymous_10(Unknown Source)
at org.mozilla.javascript.gen.file__C__Users_jzakula3_IdeaProjects_jsdoc_3_3_0_alpha13_cli_js_19.call(Unknown Source)
at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
at org.mozilla.javascript.gen.file__C__Users_jzakula3_IdeaProjects_jsdoc_3_3_0_alpha13_jsdoc_js_1._c_anonymous_3(Unknown Source)
at org.mozilla.javascript.gen.file__C__Users_jzakula3_IdeaProjects_jsdoc_3_3_0_alpha13_jsdoc_js_1.call(Unknown Source)
at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23)
at org.mozilla.javascript.gen.file__C__Users_jzakula3_IdeaProjects_jsdoc_3_3_0_alpha13_jsdoc_js_1._c_script_0(Unknown Source)
at org.mozilla.javascript.gen.file__C__Users_jzakula3_IdeaProjects_jsdoc_3_3_0_alpha13_jsdoc_js_1.call(Unknown Source)
at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3090)
at org.mozilla.javascript.gen.file__C__Users_jzakula3_IdeaProjects_jsdoc_3_3_0_alpha13_jsdoc_js_1.call(Unknown Source)
at org.mozilla.javascript.gen.file__C__Users_jzakula3_IdeaProjects_jsdoc_3_3_0_alpha13_jsdoc_js_1.exec(Unknown Source)
at org.mozilla.javascript.commonjs.module.Require.executeModuleScript(Require.java:355)
at org.mozilla.javascript.commonjs.module.Require.getExportedModuleInterface(Require.java:288)
at org.mozilla.javascript.commonjs.module.Require.requireMain(Require.java:137)
at org.mozilla.javascript.tools.shell.Main.processSource(Main.java:525)
at org.mozilla.javascript.tools.shell.Main.processFiles(Main.java:176)
at org.mozilla.javascript.tools.shell.Main$IProxy.run(Main.java:100)
at org.mozilla.javascript.Context.call(Context.java:489)
at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:504)
at org.mozilla.javascript.tools.shell.Main.exec(Main.java:158)
at org.mozilla.javascript.tools.shell.Main.main(Main.java:136)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -2
at java.lang.String.substring(Unknown Source)
at org.jsdoc.AstBuilder.processComment(AstBuilder.java:603)
at org.jsdoc.AstBuilder.processNode(AstBuilder.java:394)
at org.jsdoc.AstBuilder.access$000(AstBuilder.java:32)
at org.jsdoc.AstBuilder$1.visit(AstBuilder.java:311)
at org.mozilla.javascript.ast.AstRoot.visitComments(AstRoot.java:97)
at org.jsdoc.AstBuilder.processAllComments(AstBuilder.java:319)
at org.jsdoc.AstBuilder.build(AstBuilder.java:138)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
... 39 more
undefined

**Comment by hegemonic** [comment] 2015-04-16 23:53
On JSDoc 3.3.0, you're running into #903, which is a known issue on Windows. It'll be fixed before JSDoc 3.3.0 is released.

This bug only affects JSDoc when you're running it in Java. Can you run JSDoc with Node.js instead? Instructions are in the README.

Another workaround is to use npm to install the `underscore-contrib` module in JSDoc's `node_modules` directory.

Closing this issue, since it's a duplicate of #903.

**Closed by hegemonic** 2015-04-16 23:53 UTC
