### ISSUE TITLE
java.lang.Exception: Error: Module "underscore-contrib" not found.

### ISSUE THREAD

**Issue by SUXUMI** [jsdoc3/jsdoc#903] opened 2015-02-04 08:31 UTC
There is an error in jsdoc-3.3.0-beta1 (on Windows)

java.lang.Exception: Error: Module "underscore-contrib" not found.

When in jsdoc-3.3.0-alpha13 everything is fine

**Comment by hegemonic** [comment] 2015-02-05 16:47
I don't have access to a Windows machine right this second, but I'll investigate once I do.

How did you install JSDoc?

**Comment by albertols** [comment] 2015-02-06 15:02
I get actually the same error on Windows too. I installed it by using git and this command in the git shell: git clone https://github.com/jsdoc3/jsdoc.git

Cheers

**Comment by SUXUMI** [comment] 2015-02-06 19:36
I just unpacked downloaded files and executed jsdoc.cmd through the cmd.exe

**Comment by hegemonic** [comment] 2015-02-08 20:43
Okay, I've reproduced this issue on Windows. I'll investigate.

**Comment by jaydunning** [comment] 2015-02-13 14:02
Workaround: If you have Node.js installed, in project root directory, run `npm install underscore-contrib`. If not, place underscore-contrib files in node_modules/underscore-contrib.

**Comment by hegemonic** [comment] 2015-03-02 01:49
So far I haven't had much luck figuring out what's causing this issue. If anyone else wants to have a go, take a look at [`JsDocModuleProvider#getSubmoduleUri(URI uri, URI base)`](https://github.com/jsdoc3/rhino/blob/master/src/org/jsdoc/JsDocModuleProvider.java#L135).

**Comment by Vadorequest** [comment] 2015-04-10 14:11
Indeed, running `npm install underscore-contrib` from the root of the jsdoc folder does the work.

I downloaded the JAR from GitHub, tried `npm install` but didn't work, I guess that's because there is some dependency that is somehow installed on your development environment. I advise you to just add a `underscore-contrib` dependency in your package.json so that user don't experience that anymore.

**Comment by hegemonic** [comment] 2015-05-11 01:07
Fixed on master and releases/3.3.

**Closed by hegemonic** 2015-05-11 01:07 UTC
Labels: accepted, bugfix
