### ISSUE TITLE
{@link <url>} not parsing correctly

### ISSUE THREAD

**Issue by Askelkana** [jsdoc3/jsdoc#1004] opened 2015-05-12 10:36 UTC
A jsdoc comment of the form

    {@link http://api.jquery.com/category/deferred-object/}

fails to parse correctly. Getting the error

    "Unable to parse <a..."

which would indicate that the link is actually being generated, but is then failing afterwards.

**Comment by hegemonic** [comment] 2015-05-13 01:26
I can't reproduce this issue. What version of JSDoc are you using?

**Comment by hegemonic** [comment] 2015-05-18 23:10
Closing due to lack of information. I suspect you're running into a bug that was fixed in the final release of JSDoc 3.3.0. If you're using an alpha or beta version of JSDoc, try upgrading.

**Closed by hegemonic** 2015-05-18 23:10 UTC
Labels: needmoreinfo
