### ISSUE TITLE
@namespace as a function

### ISSUE THREAD

**Issue by leepowellcouk** [jsdoc3/jsdoc#1370] opened 2017-05-26 08:21 UTC
I'm struggling to get correct output for the following:
    
    /**
     * foo
     * @param {string} a
     * @param {string} b
     */
    var foo = function (a, b) {
      //...
    }

    /**
     * bar
     * @memberof foo
     */
    foo.bar = function () {
      //...
    }

I get output for `foo` but not for `foo.bar`. If I add the @namespace tag to `foo` as so:

    /**
     * foo
     * @namespace
     * @param {string} a
     * @param {string} b
     */
    var foo = function (a, b) {
      //...
    }

    /**
     * bar
     * @memberof foo
     */
    foo.bar = function () {
      //...
    }

Then I get the static method output for `foo.bar` but I stop getting any documentation for foo i.e. the params etc.

What I would like is to document `foo` as a global, with a static method of `bar`.

**Comment by hegemonic** [comment] 2017-07-04 20:22
Duplicate of #955.

**Closed by hegemonic** 2017-07-04 20:22 UTC
