### ISSUE TITLE
Members of ES6 classes not showing in documentation

### ISSUE THREAD

**Issue by themoonrat** [jsdoc3/jsdoc#1301] opened 2016-12-20 01:43 UTC
As an example: http://pixijs.download/v4.3.0/docs/index.html and more specifically, http://pixijs.download/v4.3.0/docs/PIXI.DisplayObject.html

If you check the source code of that class via the inbuilt docs link, you can see in it's constructor that it declares member variables such as alpha, visible and renderable. But these do not show up in the generated documentation, only functions do (which makes this issue different from https://github.com/jsdoc3/jsdoc/issues/1293 I believe). Even if you add the --private flag for jsdoc, then private class functions show up in the documentation, but again, still no class member variables.

**Comment by Native-Coder** [comment] 2016-12-21 22:43
I have this same issue! been struggling with it for HOURS. I have a class that's defined inside of a module. And No matter WHAT I do, I can't get the memebers of my class to show up in the documentation.

**Comment by Native-Coder** [comment] 2016-12-27 16:50
Found a work around. Look at my last comment here

https://github.com/jsdoc3/jsdoc/issues/1293

**Comment by staff0rd** [comment] 2017-01-01 22:59
@Native-Coder your workaround is to specify @memberof explicitly on every member.  This does already in work in PIXI docs, for example take a look at [InteractionManager.moveWhenInside](https://github.com/pixijs/pixi.js/commit/5e4f05c5bd7fbffe7bcdeb46fccf17435312ffef).  

This is issue is about not having to specify it every time, as the properties should be automatically included the same way the methods are.

**Comment by cdaringe** [comment] 2017-06-03 05:07
in `3.4.3`:

- class methods are showing up in the global namespace
- they will show up in the class namespace IFF `export default` is removed

**Comment by hegemonic** [comment] 2017-07-04 03:39
This sounds like a duplicate of #1293, which is now fixed on GitHub master. The fix will be released in JSDoc 3.5.0. If you're still able to reproduce this with the current GitHub master, please provide a code sample that demonstrates the problem, and I'll reopen the issue.

**Closed by hegemonic** 2017-07-04 03:39 UTC

**Comment by cdaringe** [comment] 2017-07-04 04:13
@hegemonic, is there donation thing for this project?  it's not much, but i'd like to slap a few bucks in this project's direction.  i searched the README and issues looking for prior discussion

**Comment by hegemonic** [comment] 2017-07-04 20:17
@cdaringe, no, there's no way to donate to JSDoc, but it's very kind of you to offer! I really appreciate your support.
