### ISSUE TITLE
"Delete of an unqualified identifier in strict mode." Error 

### ISSUE THREAD

**Issue by triangle42** [jsdoc3/jsdoc#1226] opened 2016-06-13 14:42 UTC
There is no 'use strict' in my code but I  get a "Delete of an unqualified identifier in strict mode." error when running JSDoc.
See also: #1210

**Comment by hegemonic** [comment] 2016-08-27 00:02
Looks like this is a duplicate of #1210.

**Closed by hegemonic** 2016-08-27 00:02 UTC
