### ISSUE TITLE
Properties named "prototype" are not documented

### ISSUE THREAD

**Issue by dharcourt** [jsdoc3/jsdoc#1049] opened 2015-08-05 17:42 UTC
With the following source:

    /**
     * @class Foo
     */
    function Foo() {

        Object.defineProperties(this, {

            /**
             * @memberof Foo#
             * @type {Object}
             */
            bar: {
                value: Object.prototype,
                enumerable: true,
                writable: true
            }

        });

    }

JSDoc correctly documents the class "Foo" and its "bar" property:

> **Class: Foo**
>
> **Foo**
> new Foo()
> 
> > Source: foo.js, line 1
>
> **Members**
>
> bar :Object
> 
> Type:
> * Object
>
> > Source: foo.js, line 12

Renaming "bar" to "prototype", however, with no other changes, like this:

    /**
     * @class Foo
     */
    function Foo() {

        Object.defineProperties(this, {

            /**
             * @memberof Foo#
             * @type {Object}
             */
            prototype: {
                value: Object.prototype,
                enumerable: true,
                writable: true
            }

        });

    }

Causes JSDoc to ignore the property:

> **Class: Foo**
>
> **Foo**
> new Foo()
> 
> > Source: foo.js, line 1

Obviously some objects are going to have properties named "prototype", and it should be possible to document them.

**Comment by hegemonic** [comment] 2015-08-05 21:53
What version of JSDoc are you using? On master, your second example works perfectly for me--JSDoc recognizes and documents `Foo#prototype`:

![screen shot 2015-08-05 at 2 52 33 pm](https://cloud.githubusercontent.com/assets/1522391/9098936/bc995d3a-3b81-11e5-8ee5-f143f8c796b1.png)

**Comment by dharcourt** [comment] 2015-08-07 02:32
I'm using 3.3.2 and get this result:

![image](https://cloud.githubusercontent.com/assets/1391764/9127572/c5671dd0-3c71-11e5-8e83-ae8db654b734.png)

**Comment by hegemonic** [comment] 2015-08-07 22:44
Confirmed on JSDoc 3.3.2. I'll investigate.

**Comment by hegemonic** [comment] 2015-08-07 22:48
Looks like this is #891, which was fixed on master but not on releases/3.3. I'll cherry-pick the fix to the releases/3.3 branch. The fix will be included in JSDoc 3.3.3.

**Comment by hegemonic** [comment] 2015-08-07 22:56
Cherry-picked here: a93eab0b4266da1f1d024a72403b5f80f3a29256

**Closed** 2015-08-07 22:55 UTC
Labels: bugfix

**Comment by dharcourt** [comment] 2015-08-08 01:10
Thanks, this is outstanding!
