### ISSUE TITLE
Crash on comment

### ISSUE THREAD

**Issue by mlippert** [jsdoc3/jsdoc#933] opened 2015-02-28 04:19 UTC
Crash was caused by commit a86af808 _fire jsdocCommentFound and symbolFound events in the correct order (#770)_

```
org.mozilla.javascript.WrappedException: Wrapped java.lang.StringIndexOutOfBoundsException: String index out of range: -2
        at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1754)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
        at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
        at org.mozilla.javascript.gen.file__jsdoc_rhino_jsdoc_src_astbuilder_js_63._c_anonymous_2(Unknown Source)
```

When processing a file that contains only the following:

```js
foo = function foo()
{
    //
    // some comment
};
```
Actually I've reduced the case even further to a file w/ the single line:

```js
//
```
while the file with

```js
//-
```
produces the slightly different crash:

```
org.mozilla.javascript.WrappedException: Wrapped java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1754)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
        at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
        at org.mozilla.javascript.gen.file__jsdoc_rhino_jsdoc_src_astbuilder_js_63._c_anonymous_2(Unknown Source)
```

If you need my jsdoc conf file let me know.

**Comment by hegemonic** [comment] 2015-02-28 21:22
Duplicate of #920.

**Closed by hegemonic** 2015-02-28 21:22 UTC

**Comment by hegemonic** [comment] 2015-02-28 21:30
(P.S. I verified that the fix for #920 also fixes the example you provided.)

**Comment by mlippert** [comment] 2015-03-01 00:59
Thanks, Sorry for posting a duplicate, I haven't found an easy way to search.

Anyway, the fix is good. I just tested against my codebase which had 11 files that crashed before, and both the master branch and the 3.3 release branch both complete successfully now (although it takes over 6 minutes).

(as a complete non-sequitur I've been wondering if there is an option to not create the source links and associated source html files?)

Anyway thanks for the super speedy response Jeff.

**Comment by hegemonic** [comment] 2015-03-02 01:58
@mlippert Yikes, 6 minutes is a long time. Have you tried running JSDoc with Node.js, if you're able to do so? That should be a _lot_ faster.

And yes, you can disable the source links/HTML files by setting `templates.default.outputSourceFiles` to `false` in your JSDoc config file. To my surprise, this doesn't seem to be documented at all, so I'm filing a bug to add that setting to the docs.

**Comment by mlippert** [comment] 2015-03-02 23:47
Thanks for the tip on `outputSourceFiles`, works great.

I'm going to try running JSDoc w/ node, but I've got to learn a little more about using node 1st (such as how to I get the dependencies listed in the package.json) since I like being able to just checkout a commit from the git repo and try that, and that's how I've got it hooked up currrently to my code (jsdoc is a submodule of my repo and my makefile runs it).

**Comment by hegemonic** [comment] 2015-03-03 22:10
Sounds good. In case this helps you get Node.js up and running, you can `npm install` at a specific commit, like so:

    npm install https://github.com/jsdoc3/jsdoc/tarball/e2b45451
