### ISSUE TITLE
Multiple Inheritance via @implements .. Functions do not show through

### ISSUE THREAD

**Issue by mlzummo** [jsdoc3/jsdoc#1027] opened 2015-06-18 17:49 UTC
if you have this structure top level wont see 2 levels down in inheritance only 1.

Bar.js -> CommonND.js (function_a, function_b) -> Common.js (function_1, function_2)

CommonND implements .... INDCHart.js (testData, click) ... these are methods of INDCHart which do not show through to Bar.js

Bar.js shows function_a and function_b and function_1 and _2 but not the testData and click methods of INDChart

**Comment by hegemonic** [comment] 2015-06-18 23:04
I believe that this is a duplicate of #912 and/or #1019.

**Closed by hegemonic** 2015-06-18 23:04 UTC
