### ISSUE TITLE
Error occurs when a "plugins" folder exists

### ISSUE THREAD

**Issue by kruncher** [jsdoc3/jsdoc#1114] opened 2015-11-21 00:50 UTC
Command:
```
cd ~/Sites/test.dev
jsdoc . -c jsdoc.conf.json
```

Configuration file:
```
{
	"opts": {
		"recurse": true
	},
	"plugins": [
		"plugins/markdown"
	]
}
```

Directory structure:
```
test.dev/
    plugins/
        foo/
        bar/
     index.js
     jsdoc.conf.json
     package.json
```
The "plugins" folder inside "test.dev" **does not** contain a "markdown" folder.

If I rename my "plugins" folder to "pluginz" then jsdoc does not trip up.

The error:
```
Error: Cannot find module '/Users/macuser/Sites/test.dev/plugins/markdown'
    at Function.Module._resolveFilename (module.js:336:15)
    at Requizzle.requizzle (/usr/local/lib/node_modules/jsdoc/node_modules/requizzle/lib/requizzle.js:87:22)
    at infectProxy (/usr/local/lib/node_modules/jsdoc/node_modules/requizzle/lib/loader.js:82:28)
    at Module.targetModule.require (/usr/local/lib/node_modules/jsdoc/node_modules/requizzle/lib/loader.js:101:11)
    at require (module.js:384:17)
    at Object.exports.installPlugins (/usr/local/lib/node_modules/jsdoc/lib/jsdoc/plugins.js:23:18)
    at Object.module.exports.cli.createParser (/usr/local/lib/node_modules/jsdoc/cli.js:340:17)
    at module.exports.cli.main (/usr/local/lib/node_modules/jsdoc/cli.js:225:20)
    at Object.module.exports.cli.runCommand (/usr/local/lib/node_modules/jsdoc/cli.js:180:5)
    at /usr/local/lib/node_modules/jsdoc/jsdoc.js:103:9
    at Object.<anonymous> (/usr/local/lib/node_modules/jsdoc/jsdoc.js:104:3)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
```

**Comment by kruncher** [comment] 2015-11-21 01:42
The following hack-n-slash changes seems to resolve the issue:

**cli.js**
```
...
function resolvePluginPaths(paths) {
    var path = require('jsdoc/path');

    var pluginPaths = [];

    paths.forEach(function(plugin) {
        var basename = path.basename(plugin) + ".js";
        var dirname = path.dirname(plugin);
        var pluginPath = path.getResourcePath(dirname, basename);

        if (!pluginPath) {
            logger.error('Unable to find the plugin "%s"', plugin);
            return;
        }

        pluginPaths.push( pluginPath );
    });

    return pluginPaths;
}
...
```

**lib/jsdoc/path.js**
```
...
exports.getResourcePath = function(filepath, filename) {
    var result = null;

    if (filename) {
        filepath = path.join(filepath, filename);
    }

    function pathExists(_path) {
        try {
            return fs.existsSync(_path);
        }
        catch (e) {
            return false;
        }
    }

    // absolute paths are normalized by path.resolve on the first pass
    [path.dirname(env.opts.configure || ''), env.pwd, env.dirname].forEach(function(_path) {
        if (!result && _path) {
            _path = path.resolve(_path, filepath);
            if ( pathExists(_path) ) {
                result = _path;
            }
        }
    });

    return result;
};
...
```

**Comment by lukeapage** [comment] 2015-12-07 05:23
+1 this is effecting the docstrap repo

**Comment by hegemonic** [comment] 2015-12-08 00:30
I think this is a duplicate of #1081, which is now fixed. If you're still seeing this issue on GitHub master, please let me know. The fix will be included in JSDoc 3.4.1.

**Closed by hegemonic** 2015-12-08 00:30 UTC

**Comment by kruncher** [comment] 2015-12-08 01:20
Thanks! awesome, this sounds great!
I will re-test with JSDoc 3.4.1 when it becomes available :)

**Comment by hugohuynh** [comment] 2016-10-10 08:09
I tried with jsdoc 3.4.2 still get the same problem there is a folder plugins.

**Comment by ido-ofir** [comment] 2017-03-27 21:30
Still happens in 3.4.3
