### ISSUE TITLE
commentsOnly and line numbers

### ISSUE THREAD

**Issue by mboles** [jsdoc3/jsdoc#1018] opened 2015-06-02 20:08 UTC
I am using the commentsOnly plugin with JSDoc and I think it is working as it is supposed to, but I am  hoping for different behavior. When the line number is generated for the link back into the code it is providing the line number of the comment from the comments only generated file. This makes the generated links of no value as the document user will want link to the comment in the source file, not the comments only file (which is not even available as far as I can tell).

Does anyone know of a way to have the line number reported be the first line of the comment in the source file.

Thanks-
Matt

**Comment by hegemonic** [comment] 2015-06-02 21:27
Closing because this is a duplicate of a question posted to the mailing list.

**Closed by hegemonic** 2015-06-02 21:27 UTC

**Comment by thealjey** [comment] 2017-09-07 20:26
In case someone is interested, and, like me, has no idea to what mailing list @hegemonic was referring to, you can achieve the desired functionality with a custom plugin
```javascript
const {extname} = require('path');

const comment = /\/\*\*[\s\S]+?\*\//g;
const notNewline = /[^\n]/g;
const ext = '.js';

exports.handlers = {

  beforeParse(e) {
    const {filename, source} = e;

    if (ext !== extname(filename)) {
      return;
    }

    const comments = source.match(comment);

    e.source = comments
      ? source
          .split(comment)
          .reduce((res, src, i) => res + src.replace(notNewline, '') + comments[i], '')
      : source.replace(notNewline, '');
  }

};
```
