### ISSUE TITLE
Error parsing

### ISSUE THREAD

**Issue by Robin-front** [jsdoc3/jsdoc#1214] opened 2016-05-25 02:47 UTC
```js
/**
 * this is doc
 */
export default class RoleDetail extends Component {
  static propTypes = {
    params: PropTypes.object.isRequired
  }
```

then, 
> ERROR: Unable to parse /git/oms-react/src/views/teamSys/roleDetail/index.js: Line 10: Unexpected token =

**Comment by Robin-front** [comment] 2016-05-25 03:03
```js
export default class RoleDetail extends Component {
...
}
RoleDetail.propTypes = {
  params: PropTypes.object.isRequired
}
```
it's work

**Comment by hegemonic** [comment] 2016-09-12 23:49
Duplicate of #1246.

**Closed by hegemonic** 2016-09-12 23:49 UTC
